excluded:
  - Carthage
  - HSTracker/Core/Extensions/LinqExtension.swift
  - HSTracker/Core/Extensions/NSData+GZIP.swift
  - HSTrackerUITests
  - HSTrackerTests
disabled_rules:
  - cyclomatic_complexity
  - function_body_length
  - file_length
  - type_body_length
  - todo
  - identifier_name
  - function_parameter_count
  - trailing_newline
  - trailing_whitespace
  - line_length
