source 'https://rubygems.org'

gem 'rake'
gem 'cdq'
gem 'motion-kit'
gem 'motion-kit-events'
gem 'sugarcube', require: 'sugarcube-all', github: 'rubymotion/sugarcube'
gem 'motion-cocoapods'
gem 'motion_print'
gem 'MotionLocalize'
gem 'dotenv'
gem 'motion-env'
gem 'motion-sparkle', github: 'webcracy/motion-sparkle'
gem 'redcarpet'
gem 'motion-support'
