source 'https://rubygems.org'

gem 'rake'
gem 'cdq'
gem 'motion-kit'
gem 'motion-kit-events'
gem 'sugarcube', require: 'sugarcube-all', github: 'rubymotion/sugarcube'
gem 'cocoapods'
gem 'motion-logger'
gem 'motion_print'
gem 'MotionLocalize'
