/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.Collectible {
    struct Deathknight {
        static let TheLichKingHeroHeroSkins = "HERO_11"
        static let ReapWhatYouSow = "WW_352"
        static let SkeletonCrew = "WW_322"
        static let ColdFeet = "JAM_006"
        static let ElizaGoreblade = "VAC_426"
        static let FrozenOver = "TTN_744"
        static let HarrowingOx = "WW_356"
        static let Helya = "TTN_850"
        static let PileOfBones = "WW_324"
    }
}

extension CardIds.NonCollectible {
    struct Deathknight {
        static let Helya_PlightOfTheDeadEnchantment = "TTN_850e1"
        static let DistressedKvaldir_FrostPlagueToken = "TTN_450t3"
        static let DistressedKvaldir_BloodPlagueToken = "TTN_450t"
        static let DistressedKvaldir_UnholyPlagueToken = "TTN_450t2"
        static let FrozenOver_FrozenSolidEnchantment = "TTN_744e1"
        static let HarrowingOx_OxChillEnchantment = "WW_356e"
        static let Helya_HelyaEnchantment = "TTN_850e1"
        static let PileofBones_PileOfBonesEnchantment = "WW_324e"
        static let KoboldMiner_TheAzeriteRatToken = "WW_001t26"
    }
}

