/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.NonCollectible {
    struct Deathknight {
        static let SoldiersOfTheColdDark = "FB_LK001"
        static let RemorselessWinterTavernBrawl = "FB_LK005"
        static let ToMyAidUnderling = "FB_LK006"
        static let TheLichKing_FrostmourneToken = "ICC_314t1"
        static let TheLichKing_ArmyOfTheDeadToken = "ICC_314t2"
        static let TheLichKing_DoomPactToken = "ICC_314t3"
        static let TheLichKing_DeathGripToken = "ICC_314t4"
        static let TheLichKing_DeathCoilToken = "ICC_314t5"
        static let TheLichKing_ObliterateToken = "ICC_314t6"
        static let TheLichKing_AntiMagicShellToken2 = "ICC_314t7"
        static let TheLichKing_DeathAndDecayToken = "ICC_314t8"
        static let BloodTap = "ICCA01_003"
        static let ArmyOfTheDead = "ICCA01_004"
        static let Frostmourne1 = "ICCA01_005"
        static let Frostmourne2 = "ICCA08_020"
        static let TheTrueLich = "ICCA08_021"
        static let FallenChampions = "ICCA08_022"
        static let NecroticPlague = "ICCA08_023"
        static let NecroticPlague_PlaguedEnchantment = "ICCA08_023e"
        static let TheHunted = "ICCA08_024"
        static let PurgeTheWeak = "ICCA08_025"
        static let SoulReaper = "ICCA08_026"
        static let TheTrueKing = "ICCA08_027"
        static let ThePriceOfPower = "ICCA08_028"
        static let ShutUpPriest = "ICCA08_029"
        static let RemorselessWinterICECROWN = "ICCA08_030p"
        static let AbominableKnucklesToken = "ICCA09_003t4"
    }
}

