/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.Collectible {
    struct Hunter {
        static let RamWrangler: String = "AT_010"
        static let Powershot: String = "AT_056"
        static let Stablemaster: String = "AT_057"
        static let KingsElekk: String = "AT_058"
        static let BraveArcher: String = "AT_059"
        static let BearTrap: String = "AT_060"
        static let LockAndLoad: String = "AT_061"
        static let BallOfSpiders: String = "AT_062"
        static let Acidmaw: String = "AT_063"
        static let Dreadscale: String = "AT_063t"
        static let QuickShot: String = "BRM_013"
        static let CoreRager: String = "BRM_014"
        static let HiddenCache: String = "CFM_026"
        static let Alleycat: String = "CFM_315"
        static let RatPack: String = "CFM_316"
        static let Knuckles: String = "CFM_333"
        static let SmugglersCrate: String = "CFM_334"
        static let DispatchKodo: String = "CFM_335"
        static let ShakyZipgunner: String = "CFM_336"
        static let PiranhaLauncher: String = "CFM_337"
        static let TroggBeastrager: String = "CFM_338"
        static let HuntersMark: String = "CS2_084"
        static let StarvingBuzzard: String = "CS2_237"
        static let Houndmaster: String = "DS1_070"
        static let TimberWolf: String = "DS1_175"
        static let TundraRhino: String = "DS1_178"
        static let MultiShot: String = "DS1_183"
        static let Tracking: String = "DS1_184"
        static let ArcaneShot: String = "DS1_185"
        static let GladiatorsLongbow: String = "DS1_188"
        static let ScavengingHyena: String = "EX1_531"
        static let Misdirection: String = "EX1_533"
        static let SavannahHighmane: String = "EX1_534"
        static let EaglehornBow: String = "EX1_536"
        static let ExplosiveShot: String = "EX1_537"
        static let UnleashTheHounds: String = "EX1_538"
        static let KillCommand: String = "EX1_539"
        static let KingKrush: String = "EX1_543"
        static let Flare: String = "EX1_544"
        static let BestialWrath: String = "EX1_549"
        static let SnakeTrap: String = "EX1_554"
        static let Snipe: String = "EX1_609"
        static let ExplosiveTrap: String = "EX1_610"
        static let FreezingTrap: String = "EX1_611"
        static let DeadlyShot: String = "EX1_617"
        static let Webspinner: String = "FP1_011"
        static let CallPet: String = "GVG_017"
        static let FeignDeath: String = "GVG_026"
        static let Glaivezooka: String = "GVG_043"
        static let KingOfBeasts: String = "GVG_046"
        static let MetaltoothLeaper: String = "GVG_048"
        static let Gahzrilla: String = "GVG_049"
        static let CobraShot: String = "GVG_073"
        static let SteamwheedleSniper: String = "GVG_087"
        static let Rexxar: String = "HERO_05"
        static let AlleriaWindrunner: String = "HERO_05a"
        static let ExplodingBloatbat: String = "ICC_021"
        static let ToxicArrow: String = "ICC_049"
        static let PlayDead: String = "ICC_052"
        static let VenomstrikeTrap: String = "ICC_200"
        static let ProfessorPutricide: String = "ICC_204"
        static let CorpseWidow: String = "ICC_243"
        static let StitchedTracker: String = "ICC_415"
        static let Bearshark: String = "ICC_419"
        static let AbominableBowman: String = "ICC_825"
        static let DeathstalkerRexxar: String = "ICC_828"
        static let CatTrick: String = "KAR_004"
        static let KindlyGrandmother: String = "KAR_005"
        static let CloakedHuntress: String = "KAR_006"
        static let DesertCamel: String = "LOE_020"
        static let DartTrap: String = "LOE_021"
        static let ExplorersHat: String = "LOE_105"
        static let AnimalCompanion: String = "NEW1_031"
        static let Infest: String = "OG_045"
        static let OnTheHunt: String = "OG_061"
        static let FieryBat: String = "OG_179"
        static let CallOfTheWild: String = "OG_211"
        static let InfestedWolf: String = "OG_216"
        static let ForlornStalker: String = "OG_292"
        static let GiantSandWorm: String = "OG_308"
        static let PrincessHuhuran: String = "OG_309"
        static let CarrionGrub: String = "OG_325"
        static let TerrorscaleStalker: String = "UNG_800"
        static let GrievousBite: String = "UNG_910"
        static let JeweledMacaw: String = "UNG_912"
        static let TolvirWarden: String = "UNG_913"
        static let RaptorHatchling: String = "UNG_914"
        static let CracklingRazormaw: String = "UNG_915"
        static let Stampede: String = "UNG_916"
        static let Dinomancy: String = "UNG_917"
        static let SwampKingDred: String = "UNG_919"
        static let TheMarshQueen: String = "UNG_920"
        static let WanderingMonster: String = "LOOT_079"
        static let RatTrap: String = "GIL_577"
        static let DireFrenzy: String = "GIL_828"
        static let PressurePlate = "ULD_152"
    }
}

extension CardIds.NonCollectible {
    struct Hunter {
        static let HuntersMark_HuntersMarkEnchantment: String = "CS2_084e"
        static let Houndmaster_MastersPresenceEnchantment: String = "DS1_070o"
        static let TimberWolf_FuriousHowlEnchantment: String = "DS1_175o"
        static let TundraRhino_ChargeEnchantment: String = "DS1_178e"
        static let SteadyShot: String = "DS1h_292"
        static let Misha: String = "NEW1_032"
        static let Leokk: String = "NEW1_033"
        static let Leokk_EyeInTheSkyEnchantment: String = "NEW1_033o"
        static let Huffer: String = "NEW1_034"
        static let GladiatorsLongbow_GladiatorsLongbowEnchantmentEnchantment: String = "DS1_188e"
        static let ScavengingHyena_WellFedEnchantment: String = "EX1_531e"
        static let SavannahHighmane_HyenaToken: String = "EX1_534t"
        static let EaglehornBow_UpgradedEnchantment: String = "EX1_536e"
        static let UnleashtheHounds_HoundToken: String = "EX1_538t"
        static let BestialWrath_BestialWrathEnchantment: String = "EX1_549o"
        static let SnakeTrap_SnakeToken: String = "EX1_554t"
        static let FreezingTrap_TrappedEnchantment: String = "EX1_611e"
        static let HemetNesingwary: String = "TU4d_001"
        static let ShotgunBlast: String = "TU4d_003"
        static let IllidanStormrage: String = "TU4e_001"
        static let Glaivezooka_GlaivezookaEnchantment: String = "GVG_043e"
        static let KingofBeasts_TheKingEnchantment: String = "GVG_046e"
        static let MetaltoothLeaper_MetalTeethEnchantment: String = "GVG_048e"
        static let Gahzrilla_MightOfZulfarrakEnchantment: String = "GVG_049e"
        static let CoreRager_PowerRagerEnchantment: String = "BRM_014e"
        static let Stablemaster_GroomedEnchantment: String = "AT_057o"
        static let LockandLoad_LockAndLoadEnchantment: String = "AT_061e"
        static let JusticarTrueheart_BallistaShot: String = "AT_132_HUNTER"
        static let SteadyShot_SteadyShotHeroSkins: String = "DS1h_292_H1"
        static let BallistaShotHeroSkins: String = "DS1h_292_H1_AT_132"
        static let HunterTavernBrawl: String = "FB_LK_Hunter_copy"
        static let NextHeroHunterEnchCopy: String = "FB_LK_Hunter_Ench_copy"
        static let NextHeroHunterEnch: String = "FB_TagTeam_Hunter_Ench"
        static let SecondClassHunterTavernBrawl: String = "TB_ClassRandom_Hunter"
        static let UnleashTheBeastsTavernBrawl: String = "TB_TagTeam_Hunter"
        static let ExplorersHat_ExplorersHatEnchantment: String = "LOE_105e"
        static let WishforCompanionship_Leokk: String = "LOEA02_10a"
        static let WishforCompanionship_Misha: String = "LOEA02_10c"
        static let OntheHunt_MastiffToken: String = "OG_061t"
        static let InfestedWolf_Spider: String = "OG_216a"
        static let CatTrick_CatInAHat: String = "KAR_004a"
        static let KindlyGrandmother_BigBadWolf: String = "KAR_005a"
        static let HiddenCache_SmugglingEnchantment: String = "CFM_026e"
        static let Alleycat_TabbycatToken: String = "CFM_315t"
        static let RatPack_RatToken: String = "CFM_316t"
        static let PiranhaLauncher_PiranhaToken: String = "CFM_337t"
        static let TroggBeastrager_SmugglingEnchantment: String = "CFM_338e"
        static let RaptorHatchling_RaptorPatriarchToken: String = "UNG_914t1"
        static let Stampede_StampedingEnchantment: String = "UNG_916e"
        static let Dinomancy_WellFedEnchantment: String = "UNG_917e"
        static let Dinomancy_DinomancyToken: String = "UNG_917t1"
        static let TheMarshQueen_QueenCarnassaToken: String = "UNG_920t1"
        static let TheMarshQueen_CarnassasBroodToken: String = "UNG_920t2"
        static let DeathstalkerRexxar_StitchedEnchantment: String = "ICC_828e"
        static let DeathstalkerRexxar_ZombeastToken: String = "ICC_828t"
        static let GiantRatHeroic: String = "LOOTA_BOSS_18h"
        static let WeeWhelpHeroic: String = "LOOTA_BOSS_44h"
    }
}

extension CardIds.Secrets {
    struct Hunter {
        static let All = [BearTrap, DartTrap, ExplosiveTrap, FreezingTrap,
                          HiddenCache, Misdirection, RatTrap, Snipe, SnakeTrap, CatTrick,
                          VenomstrikeTrap, WanderingMonster, PressurePlate]
        static let BearTrap = CardIds.Collectible.Hunter.BearTrap
        static let DartTrap = CardIds.Collectible.Hunter.DartTrap
        static let ExplosiveTrap = CardIds.Collectible.Hunter.ExplosiveTrap
        static let FreezingTrap = CardIds.Collectible.Hunter.FreezingTrap
        static let HiddenCache = CardIds.Collectible.Hunter.HiddenCache
        static let Misdirection = CardIds.Collectible.Hunter.Misdirection
        static let Snipe = CardIds.Collectible.Hunter.Snipe
        static let SnakeTrap = CardIds.Collectible.Hunter.SnakeTrap
        static let CatTrick = CardIds.Collectible.Hunter.CatTrick
        static let VenomstrikeTrap = CardIds.Collectible.Hunter.VenomstrikeTrap
        static let WanderingMonster = CardIds.Collectible.Hunter.WanderingMonster
        static let RatTrap = CardIds.Collectible.Hunter.RatTrap
        static let PressurePlate = CardIds.Collectible.Hunter.PressurePlate
    }
}
