/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.Collectible {
    struct Invalid {
        static let JimRaynor = "SC_400"
        static let LiftOff = "SC_410"
        static let PhotonCannon = "SC_753"
        static let Starport = "SC_403"
        static let Artanis = "SC_754"
        static let WarpGate = "SC_751"
        static let ChronoBoost = "SC_750"
        static let NydusWorm = "SC_015"
    }
}

extension CardIds.NonCollectible {
    struct Invalid {
        static let InnkeeperHealthSet: String = "FB_LK_BossSetup001"
        static let MassiveDifficulty: String = "FB_LK_BossSetup001a"
        static let HeroicDifficulty: String = "FB_LK_BossSetup001b"
        static let NormalDifficulty: String = "FB_LK_BossSetup001c"
        static let DiabolicalPowersTavernBrawl: String = "TB_SPT_DPromoHP"
        static let ProfessorPutricide_Festergut1 = "BG25_HERO_100_Buddy"
        static let ProfessorPutricide_Festergut2 = "BG25_HERO_100_Buddy_G"
        static let BattlecruiserToken = "SC_999t"
        static let Starport_Viking = "SC_403a"
        static let Starport_Liberator = "SC_403b"
        static let Starport_Raven2 = "SC_403c"
        static let Starport_Banshee2 = "SC_403d"
        static let Starport_Medivac2 = "SC_403f"
    }
}

