/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.Collectible {
    struct Mage {
        static let FlameLance: String = "AT_001"
        static let Effigy: String = "AT_002"
        static let FallenHero: String = "AT_003"
        static let ArcaneBlast: String = "AT_004"
        static let PolymorphBoar: String = "AT_005"
        static let DalaranAspirant: String = "AT_006"
        static let Spellslinger: String = "AT_007"
        static let ColdarraDrake: String = "AT_008"
        static let Rhonin: String = "AT_009"
        static let Flamewaker: String = "BRM_002"
        static let DragonsBreath: String = "BRM_003"
        static let FreezingPotion: String = "CFM_021"
        static let VolcanicPotion: String = "CFM_065"
        static let KabalLackey: String = "CFM_066"
        static let PotionOfPolymorph: String = "CFM_620"
        static let GreaterArcaneMissiles: String = "CFM_623"
        static let ManicSoulcaster: String = "CFM_660"
        static let Cryomancer: String = "CFM_671"
        static let InkmasterSolia: String = "CFM_687"
        static let KabalCrystalRunner: String = "CFM_760"
        static let Polymorph: String = "CS2_022"
        static let ArcaneIntellect: String = "CS2_023"
        static let Frostbolt: String = "CS2_024"
        static let ArcaneExplosion: String = "CS2_025"
        static let FrostNova: String = "CS2_026"
        static let MirrorImage: String = "CS2_027"
        static let Blizzard: String = "CS2_028"
        static let Fireball: String = "CS2_029"
        static let IceLance: String = "CS2_031"
        static let Flamestrike: String = "CS2_032"
        static let WaterElemental: String = "CS2_033"
        static let EtherealArcanist: String = "EX1_274"
        static let ConeOfCold: String = "EX1_275"
        static let ArcaneMissiles: String = "EX1_277"
        static let Pyroblast: String = "EX1_279"
        static let Counterspell: String = "EX1_287"
        static let IceBarrier: String = "EX1_289"
        static let MirrorEntity: String = "EX1_294"
        static let IceBlock: String = "EX1_295"
        static let ArchmageAntonidas: String = "EX1_559"
        static let Vaporize: String = "EX1_594"
        static let ExplosiveRunes: String = "LOOT_101"
        static let SorcerersApprentice: String = "EX1_608"
        static let KirinTorMage: String = "EX1_612"
        static let Duplicate: String = "FP1_018"
        static let Flamecannon: String = "GVG_001"
        static let Snowchugger: String = "GVG_002"
        static let UnstablePortal: String = "GVG_003"
        static let GoblinBlastmage: String = "GVG_004"
        static let EchoOfMedivh: String = "GVG_005"
        static let FlameLeviathan: String = "GVG_007"
        static let WeeSpellstopper: String = "GVG_122"
        static let SootSpewer: String = "GVG_123"
        static let JainaProudmoore: String = "HERO_08"
        static let Medivh: String = "HERO_08a"
        static let Khadgar: String = "HERO_08b"
        static let IceWalker: String = "ICC_068"
        static let GhastlyConjurer: String = "ICC_069"
        static let FrozenClone: String = "ICC_082"
        static let DoomedApprentice: String = "ICC_083"
        static let GlacialMysteries: String = "ICC_086"
        static let Coldwraith: String = "ICC_252"
        static let Simulacrum: String = "ICC_823"
        static let FrostLichJaina: String = "ICC_833"
        static let BreathOfSindragosa: String = "ICC_836"
        static let Sindragosa: String = "ICC_838"
        static let BabblingBook: String = "KAR_009"
        static let FirelandsPortal: String = "KAR_076"
        static let MedivhsValet: String = "KAR_092"
        static let ForgottenTorch: String = "LOE_002"
        static let EtherealConjurer: String = "LOE_003"
        static let AnimatedArmor: String = "LOE_119"
        static let ManaWyrm: String = "NEW1_012"
        static let Shatter: String = "OG_081"
        static let TwilightFlamecaller: String = "OG_083"
        static let DementedFrostcaller: String = "OG_085"
        static let ForbiddenFlame: String = "OG_086"
        static let ServantOfYoggSaron: String = "OG_087"
        static let CabalistsTome: String = "OG_090"
        static let Anomalus: String = "OG_120"
        static let FacelessSummoner: String = "OG_207"
        static let CultSorcerer: String = "OG_303"
        static let Spellbender: String = "tt_010"
        static let FlameGeyser: String = "UNG_018"
        static let Arcanologist: String = "UNG_020"
        static let SteamSurger: String = "UNG_021"
        static let ManaBind: String = "UNG_024"
        static let Pyros: String = "UNG_027"
        static let OpenTheWaygate: String = "UNG_028"
        static let ShimmeringTempest: String = "UNG_846"
        static let PrimordialGlyph: String = "UNG_941"
        static let MoltenReflection: String = "UNG_948"
        static let Meteor: String = "UNG_955"
        static let DeckOfWonders: String = "LOOT_106"
        static let SplittingImage: String = "TRL_400"
        static let FlameWard: String = "ULD_239"
    }
}

extension CardIds.NonCollectible {
    struct Mage {
        static let Polymorph_PolymorphEnchantment: String = "CS2_022e"
        static let Fireblast: String = "CS2_034"
        static let MirrorImage: String = "CS2_mirror"
        static let EtherealArcanist_RawPowerEnchantment: String = "EX1_274e"
        static let IceBlock_IceBlockEnchantment: String = "EX1_295o"
        static let KirinTorMage_PowerOfTheKirinTorEnchantment: String = "EX1_612o"
        static let ManaWyrm_ManaGorgedEnchantment: String = "NEW1_012o"
        static let Spellbender_Spellbender: String = "tt_010a"
        static let JainaProudmoore: String = "TU4a_006"
        static let MillhouseManastorm: String = "TU4b_001"
        static let NothThePlaguebringer: String = "NAX4_01"
        static let NothThePlaguebringerHeroic: String = "NAX4_01H"
        static let SootSpewer_OverclockedEnchantment: String = "GVG_123e"
        static let DragonsBreath_DragonsMightEnchantment: String = "BRM_003e"
        static let DalaranAspirant_PowerOfDalaranEnchantment: String = "AT_006e"
        static let JusticarTrueheart_FireblastRank2: String = "AT_132_MAGE"
        static let Fireblast_FireblastHeroSkins1: String = "CS2_034_H1"
        static let FireblastRank2HeroSkins1: String = "CS2_034_H1_AT_132"
        static let Fireblast_FireblastHeroSkins2: String = "CS2_034_H2"
        static let FireblastRank2HeroSkins2: String = "CS2_034_H2_AT_132"
        static let FrostLichJaina_IcyTouch: String = "ICC_833h"
        static let MageTavernBrawl: String = "FB_LK_Mage_copy"
        static let NextHeroMageEnchCopy: String = "FB_LK_Mage_Ench_copy"
        static let RelentlessMarch: String = "FB_LK002"
        static let NextHeroMageEnch: String = "FB_TagTeam_Mage_Ench"
        static let TagTeamIceBlock: String = "TagTeamIceBlock"
        static let KazakusTavernBrawl: String = "TB_BossRumble_003"
        static let SecondClassMageTavernBrawl: String = "TB_ClassRandom_Mage"
        static let FireblastTavernBrawl: String = "TB_LevelUp_002"
        static let ElementalSecretsTavernBrawl: String = "TB_TagTeam_Mage"
        static let ForgottenTorch_RoaringTorchToken: String = "LOE_002t"
        static let Medivh: String = "KARA_00_03"
        static let MedivhHeroic: String = "KARA_00_03H"
        static let ArchmagesInsight: String = "KARA_00_05"
        static let ArcanePower: String = "KARA_00_06"
        static let AstralPortal: String = "KARA_00_07"
        static let ArchmagesApprentice: String = "KARA_00_08"
        static let MageArmor: String = "KARA_00_09"
        static let MysteriousRune: String = "KARA_00_10"
        static let Evocation: String = "KARA_00_11"
        static let ShadeOfAran: String = "KARA_12_01"
        static let ShadeOfAranHeroic: String = "KARA_12_01H"
        static let FlameWreath: String = "KARA_12_03"
        static let FlameWreathHeroic: String = "KARA_12_03H"
        static let InkmasterSolia_FreeSpellEnchantment: String = "CFM_687e"
        static let Pyros_PyrosToken1: String = "UNG_027t2"
        static let Pyros_PyrosToken2: String = "UNG_027t4"
        static let OpentheWaygate_InsightfulEnchantment: String = "UNG_028e"
        static let OpentheWaygate_TimeWarpToken: String = "UNG_028t"
        static let PrimordialGlyph_PrimalMagicEnchantment: String = "UNG_941e"
        static let FrostLichJaina_WaterElementalToken: String = "ICC_833t"
        static let Sindragosa_FrozenChampionToken: String = "ICC_838t"
        static let UnchainedMagic: String = "ICCA04_002"
        static let DeckofWondersScrollOfWonderToken: String = "LOOT_106t"
    }
}

extension CardIds.Secrets {
    struct Mage {
        static let All = [Counterspell, Duplicate, Effigy, ExplosiveRunes, FrozenClone, IceBarrier,
                          IceBlock, ManaBind, MirrorEntity, PotionOfPolymorph, Spellbender,
                          SplittingImage, Vaporize, FlameWard]
        static let Counterspell = CardIds.Collectible.Mage.Counterspell
        static let Duplicate = CardIds.Collectible.Mage.Duplicate
        static let Effigy = CardIds.Collectible.Mage.Effigy
        static let FrozenClone = CardIds.Collectible.Mage.FrozenClone
        static let IceBarrier = CardIds.Collectible.Mage.IceBarrier
        static let IceBlock = CardIds.Collectible.Mage.IceBlock
        static let ManaBind = CardIds.Collectible.Mage.ManaBind
        static let MirrorEntity = CardIds.Collectible.Mage.MirrorEntity
        static let PotionOfPolymorph = CardIds.Collectible.Mage.PotionOfPolymorph
        static let Spellbender = CardIds.Collectible.Mage.Spellbender
        static let SplittingImage = CardIds.Collectible.Mage.SplittingImage
        static let Vaporize = CardIds.Collectible.Mage.Vaporize
        static let ExplosiveRunes = CardIds.Collectible.Mage.ExplosiveRunes
        static let FlameWard = CardIds.Collectible.Mage.FlameWard
    }
}
