/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.Collectible {
    struct Paladin {
        static let CompetitiveSpirit = "AT_073"
        static let SealOfChampions = "AT_074"
        static let WarhorseTrainer = "AT_075"
        static let MurlocKnight = "AT_076"
        static let ArgentLance = "AT_077"
        static let EnterTheColiseum = "AT_078"
        static let MysteriousChallenger = "AT_079"
        static let EadricThePure = "AT_081"
        static let TuskarrJouster = "AT_104"
        static let SolemnVigil = "BRM_001"
        static let DragonConsort = "BRM_018"
        static let GrimestreetProtector = "CFM_062"
        static let SmugglersRun = "CFM_305"
        static let GrimestreetEnforcer = "CFM_639"
        static let GrimscaleChum = "CFM_650"
        static let GrimestreetOutfitter = "CFM_753"
        static let MeanstreetMarshal = "CFM_759"
        static let GetawayKodo = "CFM_800"
        static let WickerflameBurnbristle = "CFM_815"
        static let SmallTimeRecruits = "CFM_905"
        static let BlessingOfMight = "CS2_087"
        static let GuardianOfKings = "CS2_088"
        static let HolyLight = "CS2_089"
        static let LightsJustice = "CS2_091"
        static let BlessingOfKings = "CS2_092"
        static let Consecration = "CS2_093"
        static let HammerOfWrath = "CS2_094"
        static let TruesilverChampion = "CS2_097"
        static let NobleSacrifice = "EX1_130"
        static let EyeForAnEye = "EX1_132"
        static let Redemption = "EX1_136"
        static let DivineFavor = "EX1_349"
        static let LayOnHands = "EX1_354"
        static let BlessedChampion = "EX1_355"
        static let Humility = "EX1_360"
        static let ArgentProtector = "EX1_362"
        static let BlessingOfWisdom = "EX1_363"
        static let HolyWrath = "EX1_365"
        static let SwordOfJustice = "EX1_366"
        static let HandOfProtection = "EX1_371"
        static let Repentance = "EX1_379"
        static let AldorPeacekeeper = "EX1_382"
        static let TirionFordring = "EX1_383"
        static let AvengingWrath = "EX1_384"
        static let Equality = "EX1_619"
        static let Avenge = "FP1_020"
        static let SealOfLight = "GVG_057"
        static let ShieldedMinibot = "GVG_058"
        static let Coghammer = "GVG_059"
        static let Quartermaster = "GVG_060"
        static let MusterForBattle = "GVG_061"
        static let CobaltGuardian = "GVG_062"
        static let BolvarFordragon = "GVG_063"
        static let ScarletPurifier = "GVG_101"
        static let UtherLightbringer = "HERO_04"
        static let LadyLiadrin = "HERO_04a"
        static let PrinceArthas = "HERO_04b"
        static let ArrogantCrusader = "ICC_034"
        static let RighteousProtector = "ICC_038"
        static let DarkConviction = "ICC_039"
        static let LightsSorrow = "ICC_071"
        static let DesperateStand = "ICC_244"
        static let Blackguard = "ICC_245"
        static let HowlingCommander = "ICC_801"
        static let ChillbladeChampion = "ICC_820"
        static let UtherOfTheEbonBlade = "ICC_829"
        static let BolvarFireblood = "ICC_858"
        static let NightbaneTemplar = "KAR_010"
        static let IvoryKnight = "KAR_057"
        static let SilvermoonPortal = "KAR_077"
        static let KeeperOfUldaman = "LOE_017"
        static let AnyfinCanHappen = "LOE_026"
        static let SacredTrial = "LOE_027"
        static let VilefinInquisitor = "OG_006"
        static let ForbiddenHealing = "OG_198"
        static let SelflessHero = "OG_221"
        static let RallyingBlade = "OG_222"
        static let DivineStrength = "OG_223"
        static let RagnarosLightlord = "OG_229"
        static let StandAgainstDarkness = "OG_273"
        static let StewardOfDarkshire = "OG_310"
        static let ALightInTheDarkness = "OG_311"
        static let Dinosize = "UNG_004"
        static let Hydrologist = "UNG_011"
        static let SunkeeperTarim = "UNG_015"
        static let Vinecleaver = "UNG_950"
        static let SpikeridgedSteed = "UNG_952"
        static let PrimalfinChampion = "UNG_953"
        static let TheLastKaleidosaur = "UNG_954"
        static let LostInTheJungle = "UNG_960"
        static let Adaptation = "UNG_961"
        static let LightfusedStegodon = "UNG_962"
    }
}

extension CardIds.NonCollectible {
    struct Paladin {
        static let BlessingofMight_BlessingOfMightEnchantment = "CS2_087e"
        static let BlessingofKings_BlessingOfKingsEnchantment = "CS2_092e"
        static let Reinforce = "CS2_101"
        static let Reinforce_SilverHandRecruitToken = "CS2_101t"
        static let Humility_HumilityEnchantment = "EX1_360e"
        static let NobleSacrifice_Defender = "EX1_130a"
        static let BlessedChampion_BlessedChampionEnchantment = "EX1_355e"
        static let BlessingofWisdom_BlessingOfWisdomEnchantment1 = "EX1_363e"
        static let BlessingofWisdom_BlessingOfWisdomEnchantment2 = "EX1_363e2"
        static let SwordofJustice_JusticeServedEnchantment = "EX1_366e"
        static let Repentance_RepentanceEnchantment = "EX1_379e"
        static let AldorPeacekeeper_StandDownEnchantment = "EX1_382e"
        static let TirionFordring_AshbringerToken = "EX1_383t"
        static let Equality_EqualityEnchantment = "EX1_619e"
        static let Avenge_VengeanceEnchantment = "FP1_020e"
        static let Quartermaster_WellEquippedEnchantment = "GVG_060e"
        static let ScarletPurifier_PureEnchantment = "GVG_101e"
        static let DragonConsort_UnchainedEnchantment = "BRM_018e"
        static let SealofChampions_SealOfChampionsEnchantment = "AT_074e2"
        static let WarhorseTrainer_MightOfTheHostlerEnchantment = "AT_075e"
        static let EadricthePure_PurifiedEnchantment = "AT_081e"
        static let JusticarTrueheart_TheSilverHand = "AT_132_PALADIN"
        static let Reinforce_ReinforceHeroSkins1 = "CS2_101_H1"
        static let TheSilverHandHeroSkins1 = "CS2_101_H1_AT_132"
        static let Reinforce_ReinforceHeroSkins2 = "CS2_101_H2"
        static let TheSilverHandHeroSkins2 = "CS2_101_H2_AT_132"
        static let PaladinTavernBrawl = "FB_LK_Paladin_copy"
        static let NextHeroPaladinEnchCopy = "FB_LK_Paladin_Ench_copy"
        static let NextHeroPaladinEnch = "FB_TagTeam_Paladin_Ench"
        static let HanchoTavernBrawl = "TB_BossRumble_001"
        static let SecondClassPaladinTavernBrawl = "TB_ClassRandom_Paladin"
        static let FollowMyRulesTavernBrawl = "TB_CoOpv3_200"
        static let DarkLightTavernBrawl = "TB_TagTeam_Paladin"
        static let MysteriousEScaleAtionTavernBrawl = "TB_TagTeam_Paladin"
        static let KeeperofUldaman_WatchedEnchantment = "LOE_017e"
        static let VilefinInquisitor_SilverHandMurloc = "OG_006a"
        static let VilefinInquisitor_TheTidalHand = "OG_006b"
        static let RallyingBlade_RallyEnchantment = "OG_222e"
        static let NightbaneTemplar_Whelp = "KAR_010a"
        static let SmugglersRun_SmugglingEnchantment = "CFM_305e"
        static let Dinosize_RaaaarEnchantment = "UNG_004e"
        static let SunkeeperTarim_WatchedEnchantment = "UNG_015e"
        static let SpikeridgedSteed_OnAStegodonEnchantment = "UNG_952e"
        static let PrimalfinChampion_InspiredEnchantment = "UNG_953e"
        static let TheLastKaleidosaur_GalvadonToken = "UNG_954t1"
        static let LightsSorrow_DyingLightEnchantment = "ICC_071e"
        static let DesperateStand_RedeemedEnchantment = "ICC_244e"
        static let UtheroftheEbonBlade_GraveVengeanceToken = "ICC_829t"
        static let UtheroftheEbonBlade_DeathlordNazgrimToken = "ICC_829t2"
        static let UtheroftheEbonBlade_ThorasTrollbaneToken = "ICC_829t3"
        static let UtheroftheEbonBlade_InquisitorWhitemaneToken = "ICC_829t4"
        static let UtheroftheEbonBlade_DarionMograineToken = "ICC_829t5"
        static let BolvarFireblood_FadingLightEnchantment = "ICC_858e"
        static let TirionFordring = "ICCA01_013"
    }
}

extension CardIds.Secrets {
    struct Paladin {
        static let All = [Avenge, CompetitiveSpirit, EyeForAnEye, NobleSacrifice,
                          Redemption, Repentance, SacredTrial, GetawayKodo]
        static let Avenge = CardIds.Collectible.Paladin.Avenge
        static let CompetitiveSpirit = CardIds.Collectible.Paladin.CompetitiveSpirit
        static let EyeForAnEye = CardIds.Collectible.Paladin.EyeForAnEye
        static let GetawayKodo = CardIds.Collectible.Paladin.GetawayKodo
        static let NobleSacrifice = CardIds.Collectible.Paladin.NobleSacrifice
        static let Redemption = CardIds.Collectible.Paladin.Redemption
        static let Repentance = CardIds.Collectible.Paladin.Repentance
        static let SacredTrial = CardIds.Collectible.Paladin.SacredTrial
    }
}
