/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.Collectible {
    struct Paladin {
        static let CompetitiveSpirit: String = "AT_073"
        static let SealOfChampions: String = "AT_074"
        static let WarhorseTrainer: String = "AT_075"
        static let MurlocKnight: String = "AT_076"
        static let ArgentLance: String = "AT_077"
        static let EnterTheColiseum: String = "AT_078"
        static let MysteriousChallenger: String = "AT_079"
        static let EadricThePure: String = "AT_081"
        static let TuskarrJouster: String = "AT_104"
        static let SolemnVigil: String = "BRM_001"
        static let DragonConsort: String = "BRM_018"
        static let GrimestreetProtector: String = "CFM_062"
        static let SmugglersRun: String = "CFM_305"
        static let GrimestreetEnforcer: String = "CFM_639"
        static let GrimscaleChum: String = "CFM_650"
        static let GrimestreetOutfitter: String = "CFM_753"
        static let MeanstreetMarshal: String = "CFM_759"
        static let GetawayKodo: String = "CFM_800"
        static let WickerflameBurnbristle: String = "CFM_815"
        static let SmallTimeRecruits: String = "CFM_905"
        static let BlessingOfMight: String = "CS2_087"
        static let GuardianOfKings: String = "CS2_088"
        static let HolyLight: String = "CS2_089"
        static let LightsJustice: String = "CS2_091"
        static let BlessingOfKings: String = "CS2_092"
        static let Consecration: String = "CS2_093"
        static let HammerOfWrath: String = "CS2_094"
        static let TruesilverChampion: String = "CS2_097"
        static let NobleSacrifice: String = "EX1_130"
        static let EyeForAnEye: String = "EX1_132"
        static let Redemption: String = "EX1_136"
        static let DivineFavor: String = "EX1_349"
        static let LayOnHands: String = "EX1_354"
        static let BlessedChampion: String = "EX1_355"
        static let Humility: String = "EX1_360"
        static let ArgentProtector: String = "EX1_362"
        static let BlessingOfWisdom: String = "EX1_363"
        static let HolyWrath: String = "EX1_365"
        static let SwordOfJustice: String = "EX1_366"
        static let HandOfProtection: String = "EX1_371"
        static let Repentance: String = "EX1_379"
        static let AldorPeacekeeper: String = "EX1_382"
        static let TirionFordring: String = "EX1_383"
        static let AvengingWrath: String = "EX1_384"
        static let Equality: String = "EX1_619"
        static let Avenge: String = "FP1_020"
        static let SealOfLight: String = "GVG_057"
        static let ShieldedMinibot: String = "GVG_058"
        static let Coghammer: String = "GVG_059"
        static let Quartermaster: String = "GVG_060"
        static let MusterForBattle: String = "GVG_061"
        static let CobaltGuardian: String = "GVG_062"
        static let BolvarFordragon: String = "GVG_063"
        static let ScarletPurifier: String = "GVG_101"
        static let UtherLightbringer: String = "HERO_04"
        static let LadyLiadrin: String = "BT_334"
        static let PrinceArthas: String = "HERO_04b"
        static let ArrogantCrusader: String = "ICC_034"
        static let RighteousProtector: String = "ICC_038"
        static let DarkConviction: String = "ICC_039"
        static let LightsSorrow: String = "ICC_071"
        static let DesperateStand: String = "ICC_244"
        static let Blackguard: String = "ICC_245"
        static let HowlingCommander: String = "ICC_801"
        static let ChillbladeChampion: String = "ICC_820"
        static let UtherOfTheEbonBlade: String = "ICC_829"
        static let BolvarFireblood: String = "ICC_858"
        static let NightbaneTemplar: String = "KAR_010"
        static let IvoryKnight: String = "KAR_057"
        static let SilvermoonPortal: String = "KAR_077"
        static let KeeperOfUldaman: String = "LOE_017"
        static let AnyfinCanHappen: String = "LOE_026"
        static let SacredTrial: String = "LOE_027"
        static let VilefinInquisitor: String = "OG_006"
        static let ForbiddenHealing: String = "OG_198"
        static let SelflessHero: String = "OG_221"
        static let RallyingBlade: String = "OG_222"
        static let DivineStrength: String = "OG_223"
        static let RagnarosLightlord: String = "OG_229"
        static let StandAgainstDarkness: String = "OG_273"
        static let StewardOfDarkshire: String = "OG_310"
        static let ALightInTheDarkness: String = "OG_311"
        static let Dinosize: String = "UNG_004"
        static let Hydrologist: String = "UNG_011"
        static let SunkeeperTarim: String = "UNG_015"
        static let Vinecleaver: String = "UNG_950"
        static let SpikeridgedSteed: String = "UNG_952"
        static let PrimalfinChampion: String = "UNG_953"
        static let TheLastKaleidosaur: String = "UNG_954"
        static let LostInTheJungle: String = "UNG_960"
        static let Adaptation: String = "UNG_961"
        static let LightfusedStegodon: String = "UNG_962"
        static let HiddenWisdom: String = "GIL_903"
        static let AutodefenseMatrix: String = "BOT_908"
        static let NeverSurrender = "DAL_570"
        static let SandwaspQueen = "ULD_439"
        static let OhMyYogg = "DMF_236"
        static let ImmortalPrelate = "TRL_306"
        static let MurgurMurgurgle = "BT_019"
        static let ParagonOfLight = "GIL_685"
        static let FarrakiBattleaxe = "TRL_304"
        static let Bloodclaw = "TRL_543"
        static let FlashOfLight = "TRL_307"
        static let BenevolentDjinn = "LOOT_398"
        static let PotionOfHeroism = "LOOT_088"
        static let AvengeCore = "CORE_FP1_020"
        static let EyeForAnEyeVanilla = "VAN_EX1_132"
        static let NobleSacrificeCore = "CORE_EX1_130"
        static let NobleSacrificeVanilla = "VAN_EX1_130"
        static let RedemptionVanilla = "VAN_EX1_136"
        static let RepentanceVanilla = "VAN_EX1_379"
        static let ReckoningCore = "CS3_016"
        static let GallopingSavior = "BAR_550"
        static let ConvictionRank1 = "BAR_880"
        static let AldorAttendant = "BT_020"
        static let AldorTruthseeker = "BT_026"
        static let JudgmentOfJustice = "WC_033"
        static let AzsharanMooncatcher = "TSC_644"
        static let SinfulSousChef = "REV_952"
        static let TheCountess = "REV_951"
        static let FossilizedKaleidosaur = "DEEP_033"
        static let Shroomscavate = "DEEP_018"
        static let LifesavingAura = "VAC_922"
        static let CrusaderAuraCore = "TTN_908"
        static let DeputizationAura = "WW_341"
        static let HolyCowboy = "WW_335"
        static let InventorsAura = "TTN_854"
        static let Lifeguard = "VAC_919"
        static let Rebuke = "GIL_203"
        static let ResistanceAuraCore = "TTN_851"
        static let StarlightGroove = "ETC_330"
        static let TimeOut = "TRL_302"
        static let Timewarden = "RLK_527"
        static let WaveOfApathy = "SCH_250"
        static let LibramOfWisdom = "BT_025"
        static let LibramOfClarity = "GDB_137"
        static let LibramOfDivinity = "GDB_138"
        static let LibramOfFaith = "GDB_139"
        static let LibramOfJustice = "BT_011"
        static let LibramOfJudgment = "YOP_011"
        static let LibramOfHope = "BT_024"
        static let LadyLiadrinCore = "CORE_BT_334"
        static let Tyr = "TTN_857"
        static let TyrsTears_TyrsTearsToken = "TTN_855t"
    }
}

extension CardIds.NonCollectible {
    struct Paladin {
        static let Grillmaster_SunscreenToken = "VAC_917t"
        static let BlessingofMight_BlessingOfMightEnchantment: String = "CS2_087e"
        static let BlessingofKings_BlessingOfKingsEnchantment: String = "CS2_092e"
        static let Reinforce: String = "CS2_101"
        static let Reinforce_SilverHandRecruitToken: String = "CS2_101t"
        static let Humility_HumilityEnchantment: String = "EX1_360e"
        static let NobleSacrifice_Defender: String = "EX1_130a"
        static let BlessedChampion_BlessedChampionEnchantment: String = "EX1_355e"
        static let BlessingofWisdom_BlessingOfWisdomEnchantment1: String = "EX1_363e"
        static let BlessingofWisdom_BlessingOfWisdomEnchantment2: String = "EX1_363e2"
        static let SwordofJustice_JusticeServedEnchantment: String = "EX1_366e"
        static let Repentance_RepentanceEnchantment: String = "EX1_379e"
        static let AldorPeacekeeper_StandDownEnchantment: String = "EX1_382e"
        static let TirionFordring_AshbringerToken: String = "EX1_383t"
        static let Equality_EqualityEnchantment: String = "EX1_619e"
        static let Avenge_VengeanceEnchantment: String = "FP1_020e"
        static let Quartermaster_WellEquippedEnchantment: String = "GVG_060e"
        static let ScarletPurifier_PureEnchantment: String = "GVG_101e"
        static let DragonConsort_UnchainedEnchantment: String = "BRM_018e"
        static let SealofChampions_SealOfChampionsEnchantment: String = "AT_074e2"
        static let WarhorseTrainer_MightOfTheHostlerEnchantment: String = "AT_075e"
        static let EadricthePure_PurifiedEnchantment: String = "AT_081e"
        static let JusticarTrueheart_TheSilverHand: String = "AT_132_PALADIN"
        static let Reinforce_ReinforceHeroSkins1: String = "CS2_101_H1"
        static let TheSilverHandHeroSkins1: String = "CS2_101_H1_AT_132"
        static let Reinforce_ReinforceHeroSkins2: String = "CS2_101_H2"
        static let TheSilverHandHeroSkins2: String = "CS2_101_H2_AT_132"
        static let PaladinTavernBrawl: String = "FB_LK_Paladin_copy"
        static let NextHeroPaladinEnchCopy: String = "FB_LK_Paladin_Ench_copy"
        static let NextHeroPaladinEnch: String = "FB_TagTeam_Paladin_Ench"
        static let HanchoTavernBrawl: String = "TB_BossRumble_001"
        static let SecondClassPaladinTavernBrawl: String = "TB_ClassRandom_Paladin"
        static let FollowMyRulesTavernBrawl: String = "TB_CoOpv3_200"
        static let DarkLightTavernBrawl: String = "TB_TagTeam_Paladin"
        static let MysteriousEScaleAtionTavernBrawl: String = "TB_TagTeam_Paladin"
        static let KeeperofUldaman_WatchedEnchantment: String = "LOE_017e"
        static let VilefinInquisitor_SilverHandMurloc: String = "OG_006a"
        static let VilefinInquisitor_TheTidalHand: String = "OG_006b"
        static let RallyingBlade_RallyEnchantment: String = "OG_222e"
        static let NightbaneTemplar_Whelp: String = "KAR_010a"
        static let SmugglersRun_SmugglingEnchantment: String = "CFM_305e"
        static let Dinosize_RaaaarEnchantment: String = "UNG_004e"
        static let SunkeeperTarim_WatchedEnchantment: String = "UNG_015e"
        static let SpikeridgedSteed_OnAStegodonEnchantment: String = "UNG_952e"
        static let PrimalfinChampion_InspiredEnchantment: String = "UNG_953e"
        static let TheLastKaleidosaur_GalvadonToken: String = "UNG_954t1"
        static let LightsSorrow_DyingLightEnchantment: String = "ICC_071e"
        static let DesperateStand_RedeemedEnchantment: String = "ICC_244e"
        static let UtheroftheEbonBlade_GraveVengeanceToken: String = "ICC_829t"
        static let UtheroftheEbonBlade_DeathlordNazgrimToken: String = "ICC_829t2"
        static let UtheroftheEbonBlade_ThorasTrollbaneToken: String = "ICC_829t3"
        static let UtheroftheEbonBlade_InquisitorWhitemaneToken: String = "ICC_829t4"
        static let UtheroftheEbonBlade_DarionMograineToken: String = "ICC_829t5"
        static let BolvarFireblood_FadingLightEnchantment: String = "ICC_858e"
        static let TirionFordring: String = "ICCA01_013"
        static let HandOfSalvation: String = "BCON_012"
        static let SandwaspQueen_SandwaspToken: String = "ULD_439t"
        static let MurgurMurgurgle_MurgurglePrimeToken = "BT_019t"
        static let ShirvallahsProtection = "TRLA_105"
        static let ShirvallahsVengeance = "TRLA_137"
        static let ShirvallahsGrace = "TRLA_138"
        static let ConvictionRank1_ConvictionRank2Token = "BAR_880t"
        static let ConvictionRank1_ConvictionRank3Token = "BAR_880t2"
        static let AzsharanMooncatcher_SunkenMooncatcherToken = "TSC_644t"
        static let SilverHandRecruitLegacyToken = "CS2_101t"
        static let TheCountess_LegendaryInvitationToken = "REV_951t"
        static let DeputizationAura_MyFavoriteDeputyEnchantment = "WW_341e"
        static let HolyCowboy_HolyCowboyEnchantment = "WW_335e"
        static let InventorsAura_EmpoweredWorkshopEnchantment = "TTN_854e"
        static let Lifeguard_ProtectionEnchantment = "VAC_919e"
        static let Timewarden_FromTheFutureEnchantment = "RLK_527e2"
        static let TimeOut_TimeOutEnchantment = "TRL_302e"
        static let StarlightGroove_FeelingTheGrooveEnchantment = "ETC_330e1"
        static let ResistanceAura_ResistanceCoreEnchantment = "TTN_851e"
        static let TheAzeriteDragonToken = "DEEP_999t4"
        static let InterstellarStarslicer_InterstellarLibramEnchantmentEnchantment = "GDB_726e"
        static let TyrsTears = "TTN_855"
    }
}

extension CardIds.Secrets {
    struct Paladin {
        static let All = [AutodefenseMatrix, Avenge, CompetitiveSpirit, EyeForAnEye, GetawayKodo, GallopingSavior, HandOfSalvation, HiddenWisdom, NeverSurrender, NobleSacrifice, OhMyYogg, Reckoning, Redemption, Repentance, SacredTrial, JudgementofJustice ]
        static let AutodefenseMatrix = MultiIdCard(CardIds.Collectible.Paladin.AutodefenseMatrix)
        static let Avenge = MultiIdCard(CardIds.Collectible.Paladin.Avenge, CardIds.Collectible.Paladin.AvengeCore)
        static let CompetitiveSpirit = MultiIdCard(CardIds.Collectible.Paladin.CompetitiveSpirit)
        static let EyeForAnEye = MultiIdCard(CardIds.Collectible.Paladin.EyeForAnEye, CardIds.Collectible.Paladin.EyeForAnEyeVanilla)
        static let GallopingSavior = MultiIdCard(CardIds.Collectible.Paladin.GallopingSavior)
        static let GetawayKodo = MultiIdCard(CardIds.Collectible.Paladin.GetawayKodo)
        static let HandOfSalvation = MultiIdCard(CardIds.NonCollectible.Paladin.HandOfSalvation)
        static let HiddenWisdom = MultiIdCard(CardIds.Collectible.Paladin.HiddenWisdom)
        static let NeverSurrender = MultiIdCard(CardIds.Collectible.Paladin.NeverSurrender)
        static let NobleSacrifice = MultiIdCard(CardIds.Collectible.Paladin.NobleSacrifice, CardIds.Collectible.Paladin.NobleSacrificeCore, CardIds.Collectible.Paladin.NobleSacrificeVanilla)
        static let OhMyYogg = MultiIdCard(CardIds.Collectible.Paladin.OhMyYogg)
        static let Reckoning = MultiIdCard(CardIds.Collectible.Paladin.ReckoningCore)
        static let Redemption = MultiIdCard(CardIds.Collectible.Paladin.Redemption, CardIds.Collectible.Paladin.RedemptionVanilla)
        static let Repentance = MultiIdCard(CardIds.Collectible.Paladin.Repentance, CardIds.Collectible.Paladin.RepentanceVanilla)
        static let SacredTrial = MultiIdCard(CardIds.Collectible.Paladin.SacredTrial)
        static let JudgementofJustice = MultiIdCard(CardIds.Collectible.Paladin.JudgmentOfJustice)
    }
}
