/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.Collectible {
    struct Priest {
        static let HolyChampion: String = "AT_011"
        static let SpawnOfShadows: String = "AT_012"
        static let PowerWordGlory: String = "AT_013"
        static let Shadowfiend: String = "AT_014"
        static let Convert: String = "AT_015"
        static let Confuse: String = "AT_016"
        static let ConfessorPaletress: String = "AT_018"
        static let FlashHeal: String = "AT_055"
        static let WyrmrestAgent: String = "AT_116"
        static let TwilightWhelp: String = "BRM_004"
        static let Resurrect: String = "BRM_017"
        static let RazaTheChained: String = "CFM_020"
        static let PotionOfMadness: String = "CFM_603"
        static let GreaterHealingPotion: String = "CFM_604"
        static let DrakonidOperative: String = "CFM_605"
        static let ManaGeode: String = "CFM_606"
        static let KabalTalonpriest: String = "CFM_626"
        static let KabalSongstealer: String = "CFM_657"
        static let PintSizePotion: String = "CFM_661"
        static let DragonfirePotion: String = "CFM_662"
        static let HolyNova: String = "CS1_112"
        static let MindControl: String = "CS1_113"
        static let InnerFire: String = "CS1_129"
        static let HolySmite: String = "CS1_130"
        static let MindVision: String = "CS2_003"
        static let PowerWordShield: String = "CS2_004"
        static let ShadowWordPain: String = "CS2_234"
        static let NorthshireCleric: String = "CS2_235"
        static let DivineSpirit: String = "CS2_236"
        static let MindBlast: String = "DS1_233"
        static let CabalShadowPriest: String = "EX1_091"
        static let Silence: String = "EX1_332"
        static let ShadowMadness: String = "EX1_334"
        static let Lightspawn: String = "EX1_335"
        static let Thoughtsteal: String = "EX1_339"
        static let Lightwell: String = "EX1_341"
        static let Mindgames: String = "EX1_345"
        static let ProphetVelen: String = "EX1_350"
        static let AuchenaiSoulpriest: String = "EX1_591"
        static let CircleOfHealing: String = "EX1_621"
        static let ShadowWordDeath: String = "EX1_622"
        static let TempleEnforcer: String = "EX1_623"
        static let HolyFire: String = "EX1_624"
        static let Shadowform: String = "EX1_625"
        static let MassDispel: String = "EX1_626"
        static let DarkCultist: String = "FP1_023"
        static let Lightbomb: String = "GVG_008"
        static let Shadowbomber: String = "GVG_009"
        static let VelensChosen: String = "GVG_010"
        static let Shrinkmeister: String = "GVG_011"
        static let LightOfTheNaaru: String = "GVG_012"
        static let Voljin: String = "GVG_014"
        static let Shadowboxer: String = "GVG_072"
        static let UpgradedRepairBot: String = "GVG_083"
        static let AnduinWrynn: String = "HERO_09"
        static let TyrandeWhisperwind: String = "HERO_09a"
        static let DevourMind: String = "ICC_207"
        static let ShadowAscendant: String = "ICC_210"
        static let AcolyteOfAgony: String = "ICC_212"
        static let EternalServitude: String = "ICC_213"
        static let ObsidianStatue: String = "ICC_214"
        static let ArchbishopBenedictus: String = "ICC_215"
        static let ShadowEssence: String = "ICC_235"
        static let SpiritLash: String = "ICC_802"
        static let ShadowreaperAnduin: String = "ICC_830"
        static let EmbraceDarkness: String = "ICC_849"
        static let Purify: String = "KAR_013"
        static let PriestOfTheFeast: String = "KAR_035"
        static let OnyxBishop: String = "KAR_204"
        static let MuseumCurator: String = "LOE_006"
        static let Entomb: String = "LOE_104"
        static let ExcavatedEvil: String = "LOE_111"
        static let PowerWordTentacles: String = "OG_094"
        static let TwilightDarkmender: String = "OG_096"
        static let ShadowWordHorror: String = "OG_100"
        static let ForbiddenShaping: String = "OG_101"
        static let EmbraceTheShadow: String = "OG_104"
        static let DarkshireAlchemist: String = "OG_234"
        static let HeraldVolazj: String = "OG_316"
        static let HoodedAcolyte: String = "OG_334"
        static let ShiftingShade: String = "OG_335"
        static let MirageCaller: String = "UNG_022"
        static let ShadowVisions: String = "UNG_029"
        static let BindingHeal: String = "UNG_030"
        static let CrystallineOracle: String = "UNG_032"
        static let RadiantElemental: String = "UNG_034"
        static let CuriousGlimmerroot: String = "UNG_035"
        static let TortollanShellraiser: String = "UNG_037"
        static let FreeFromAmber: String = "UNG_854"
        static let AwakenTheMakers: String = "UNG_940"
        static let LyraTheSunshard: String = "UNG_963"
        static let GildedGargoyle: String = "LOOT_534"
        static let Chameleos: String = "GIL_142"
        static let ExtraArms: String = "BOT_219"
        static let SpiritOfTheDead = "TRL_502"
    }
}

extension CardIds.NonCollectible {
    struct Priest {
        static let LesserHeal: String = "CS1h_001"
        static let PowerWordShield_PowerWordShieldEnchantment: String = "CS2_004e"
        static let DivineSpirit_DivineSpiritEnchantment: String = "CS2_236e"
        static let ShatteredSunCleric_ClericsBlessingEnchantment: String = "EX1_019e"
        static let InnerFire_InnerFireEnchantment: String = "CS1_129e"
        static let ShadowMadness_ShadowMadnessEnchantment: String = "EX1_334e"
        static let Mindgames_ShadowOfNothingToken: String = "EX1_345t"
        static let TempleEnforcer_InfusionEnchantment: String = "EX1_623e"
        static let Shadowform_MindSpikeToken: String = "EX1_625t"
        static let Shadowform_MindShatterToken: String = "EX1_625t2"
        static let MindControlling: String = "EX1_tk31"
        static let DarkCultist_PowerOfTheZigguratEnchantment: String = "FP1_023e"
        static let Voljin_Shadowed: String = "GVG_014a"
        static let AntiqueHealbot_Repairs: String = "GVG_069a"
        static let SolemnVigil_MeltEnchantment: String = "BRM_001e"
        static let Shadowfiend_ShadowfiendedEnchantment: String = "AT_014e"
        static let Confuse_ConfusedEnchantment: String = "AT_016e"
        static let WyrmrestAgent_BringItOnEnchantment: String = "AT_116e"
        static let JusticarTrueheart_Heal: String = "AT_132_PRIEST"
        static let LesserHeal_LesserHealHeroSkins: String = "CS1h_001_H1"
        static let HealHeroSkins: String = "CS1h_001_H1_AT_132"
        static let PriestTavernBrawl: String = "FB_LK_Priest_copy"
        static let NextHeroPriestEnchCopy: String = "FB_LK_Priest_Ench_copy"
        static let NextHeroPriestEnch: String = "FB_TagTeam_Priest_Ench"
        static let SecondClassPriestTavernBrawl: String = "TB_ClassRandom_Priest"
        static let TwistedLightTavernBrawl: String = "TB_CoOpv3_002"
        static let ShadowOrLightTavernBrawl: String = "TB_Coopv3_102"
        static let ShadoworLight_SecretsOfShadowTavernBrawl: String = "TB_Coopv3_102a"
        static let ShadoworLight_AlmsOfLightTavernBrawl: String = "TB_Coopv3_102b"
        static let PowerWordTentacles_TentaclesEnchantment: String = "OG_094e"
        static let PotionofMadness_MadnessPotionEnchantment: String = "CFM_603e"
        static let ManaGeode_CrystalToken: String = "CFM_606t"
        static let PintSizePotion_ShrunkEnchantment: String = "CFM_661e"
        static let MirageCaller_MirageEnchantment: String = "UNG_022e"
        static let TortollanShellraiser_ShellshieldEnchantment: String = "UNG_037e"
        static let AwakentheMakers_AmaraWardenOfHopeToken: String = "UNG_940t8"
        static let ShadowAscendant_AscendedEnchantment: String = "ICC_210e"
        static let ShadowreaperAnduin_Voidform: String = "ICC_830p"
        static let ExtraArms_MoreArmsToken: String = "BOT_219t"
    }
}

