/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.Collectible {
    struct Rogue {
        static let ShadoPanRider: String = "AT_028"
        static let Buccaneer: String = "AT_029"
        static let UndercityValiant: String = "AT_030"
        static let Cutpurse: String = "AT_031"
        static let ShadyDealer: String = "AT_032"
        static let Burgle: String = "AT_033"
        static let PoisonedBlade: String = "AT_034"
        static let BeneathTheGrounds: String = "AT_035"
        static let Anubarak: String = "AT_036"
        static let GangUp: String = "BRM_007"
        static let DarkIronSkulker: String = "BRM_008"
        static let LuckydoBuccaneer: String = "CFM_342"
        static let CounterfeitCoin: String = "CFM_630"
        static let LotusAssassin: String = "CFM_634"
        static let ShadowRager: String = "CFM_636"
        static let JadeShuriken: String = "CFM_690"
        static let JadeSwarmer: String = "CFM_691"
        static let GadgetzanFerryman: String = "CFM_693"
        static let ShadowSensei: String = "CFM_694"
        static let ShakuTheCollector: String = "CFM_781"
        static let Backstab: String = "CS2_072"
        static let ColdBlood: String = "CS2_073"
        static let DeadlyPoison: String = "CS2_074"
        static let SinisterStrike: String = "CS2_075"
        static let GilblinStalker: String = "GVG_081"
        static let Assassinate: String = "CS2_076"
        static let Sprint: String = "CS2_077"
        static let AssassinsBlade: String = "CS2_080"
        static let BladeFlurry: String = "CS2_233"
        static let Eviscerate: String = "EX1_124"
        static let Betrayal: String = "EX1_126"
        static let Conceal: String = "EX1_128"
        static let FanOfKnives: String = "EX1_129"
        static let DefiasRingleader: String = "EX1_131"
        static let PerditionsBlade: String = "EX1_133"
        static let Si7Agent: String = "EX1_134"
        static let Headcrack: String = "EX1_137"
        static let Shadowstep: String = "EX1_144"
        static let Preparation: String = "EX1_145"
        static let Shiv: String = "EX1_278"
        static let PatientAssassin: String = "EX1_522"
        static let Sap: String = "EX1_581"
        static let EdwinVancleef: String = "EX1_613"
        static let AnubarAmbusher: String = "FP1_026"
        static let TinkersSharpswordOil: String = "GVG_022"
        static let GoblinAutoBarber: String = "GVG_023"
        static let CogmastersWrench: String = "GVG_024"
        static let OneEyedCheat: String = "GVG_025"
        static let IronSensei: String = "GVG_027"
        static let TradePrinceGallywix: String = "GVG_028"
        static let Sabotage: String = "GVG_047"
        static let OgreNinja: String = "GVG_088"
        static let ValeeraSanguinar: String = "HERO_03"
        static let MaievShadowsong: String = "HERO_03a"
        static let BoneBaron: String = "ICC_065"
        static let RollTheBones: String = "ICC_201"
        static let LeechingPoison: String = "ICC_221"
        static let Doomerang: String = "ICC_233"
        static let RuneforgeHaunter: String = "ICC_240"
        static let PlagueScientist: String = "ICC_809"
        static let LilianVoss: String = "ICC_811"
        static let ValeeraTheHollow: String = "ICC_827"
        static let Shadowblade: String = "ICC_850"
        static let SpectralPillager: String = "ICC_910"
        static let Swashburglar: String = "KAR_069"
        static let EtherealPeddler: String = "KAR_070"
        static let DeadlyFork: String = "KAR_094"
        static let PitSnake: String = "LOE_010"
        static let TombPillager: String = "LOE_012"
        static let UnearthedRaptor: String = "LOE_019"
        static let Vanish: String = "NEW1_004"
        static let Kidnapper: String = "NEW1_005"
        static let MasterOfDisguise: String = "NEW1_014"
        static let BladedCultist: String = "OG_070"
        static let JourneyBelow: String = "OG_072"
        static let ThistleTea: String = "OG_073"
        static let XarilPoisonedMind: String = "OG_080"
        static let ShadowStrike: String = "OG_176"
        static let SouthseaSquidface: String = "OG_267"
        static let BladeOfCthun: String = "OG_282"
        static let Shadowcaster: String = "OG_291"
        static let UndercityHuckster: String = "OG_330"
        static let RazorpetalVolley: String = "UNG_057"
        static let RazorpetalLasher: String = "UNG_058"
        static let MimicPod: String = "UNG_060"
        static let ObsidianShard: String = "UNG_061"
        static let Biteweed: String = "UNG_063"
        static let VilespineSlayer: String = "UNG_064"
        static let SherazinCorpseFlower: String = "UNG_065"
        static let TheCavernsBelow: String = "UNG_067"
        static let EnvenomWeapon: String = "UNG_823"
        static let Hallucination: String = "UNG_856"
        static let CheatDeath: String = "LOOT_204"
        static let Evasion: String = "LOOT_214"
        static let SuddenBetrayal: String = "LOOT_210"
        static let SonyaShadowdancer: String = "LOOT_165"
        static let FaldoreiStrider: String = "LOOT_026"
        static let Kingsbane: String = "LOOT_542"
        static let LabRecruiter: String = "BOT_288"
        static let ShadowOfDeath: String = "ULD_286"
    }
}

extension CardIds.NonCollectible {
    struct Rogue {
        static let WickedKnife: String = "CS2_082"
        static let DaggerMastery: String = "CS2_083b"
        static let SharpenedEnchantment: String = "CS2_083e"
        static let ColdBlood_ColdBloodEnchantment1: String = "CS2_073e"
        static let ColdBlood_ColdBloodEnchantment2: String = "CS2_073e2"
        static let DefiasRingleader_DefiasBanditToken: String = "EX1_131t"
        static let Preparation_PreparationEnchantment: String = "EX1_145o"
        static let EdwinVanCleef_VancleefsVengeanceEnchantment: String = "EX1_613e"
        static let MasterofDisguise_DisguisedEnchantment: String = "NEW1_014e"
        static let Conceal_ConcealedEnchantment: String = "EX1_128e"
        static let IronSensei_IronedOutEnchantment: String = "GVG_027e"
        static let ShadyDealer_ShadyDealsEnchantment: String = "AT_032e"
        static let PoisonedBlade_LacedEnchantment: String = "AT_034e"
        static let BeneaththeGrounds_NerubianAmbushToken: String = "AT_035t"
        static let Anubarak_NerubianToken: String = "AT_036t"
        static let JusticarTrueheart_PoisonedDaggers: String = "AT_132_ROGUE"
        static let JusticarTrueheart_PoisonedDagger: String = "AT_132_ROGUEt"
        static let RyanMasterson: String = "CRED_40"
        static let JusticarTrueheart_PoisonedDaggersHeroSkins: String = "AT_132_ROGUE_H1"
        static let JusticarTrueheart_PoisonedDaggerHeroSkins: String = "AT_132_ROGUEt_H1"
        static let WickedKnife_WickedKnifeHeroSkins: String = "CS2_082_H1"
        static let DaggerMasteryHeroSkins: String = "CS2_083b_H1"
        static let RogueTavernBrawl: String = "FB_LK_Rogue_copy"
        static let NextHeroRogueEnchCopy: String = "FB_LK_Rogue_Ench_copy"
        static let NextHeroRogueEnch: String = "FB_TagTeam_Rogue_Ench"
        static let SharpenedTavernBrawl: String = "TB_BlingBrawl_Hero1e"
        static let SharpenTavernBrawl: String = "TB_BlingBrawl_Hero1p"
        static let SecondClassRogueTavernBrawl: String = "TB_ClassRandom_Rogue"
        static let CastFromShadowTavernBrawl: String = "TB_CoOpv3_201"
        static let ShadowReflection_ShadowReflectionEnchantmentTavernBrawl: String = "TB_ShadowReflection_001e"
        static let FacilitatedTavernBrawl: String = "TB_Superfriends001e"
        static let DrawOffensivePlayTavernBrawl: String = "TB_Superfriends002e"
        static let CashIn: String = "TP_Bling_HP2"
        static let UnearthedRaptor_UnearthedRaptorEnchantment: String = "LOE_019e"
        static let BladedCultist_ThirstyBladesEnchantment: String = "OG_070e"
        static let XarilPoisonedMind_KingsbloodToxin: String = "OG_080b"
        static let XarilPoisonedMind_BloodthistleToxin: String = "OG_080c"
        static let XarilPoisonedMind_BriarthornToxin: String = "OG_080d"
        static let XarilPoisonedMind_FadeleafToxinEnchantment: String = "OG_080e"
        static let XarilPoisonedMind_FirebloomToxin: String = "OG_080f"
        static let SouthseaSquidface_SquidOilSheenEnchantment: String = "OG_267e"
        static let DeadlyFork_SharpFork: String = "KAR_094a"
        static let LuckydoBuccaneer_LootedBladeEnchantment: String = "CFM_342e"
        static let ShadowSensei_TrainedEnchantment: String = "CFM_694e"
        static let RazorpetalVolley_RazorpetalToken: String = "UNG_057t1"
        static let Biteweed_SproutEnchantment: String = "UNG_063e"
        static let SherazinCorpseFlower_SherazinSeedToken: String = "UNG_065t"
        static let TheCavernsBelow_CrystalCoreToken: String = "UNG_067t1"
        static let PhantomFreebooter_WittyWeaponplayEnchantment: String = "ICC_018e"
        static let LeechingPoison_LeechingPoisonEnchantment: String = "ICC_221e"
        static let RuneforgeHaunter_ResilientWeaponEnchantment: String = "ICC_240e"
        static let PlagueScientist_TestSubjectEnchantment: String = "ICC_809e"
        static let ValeeratheHollow_ShadowReflectionEnchantment: String = "ICC_827e"
        static let ValeeratheHollow_VeilOfShadowsEnchantment: String = "ICC_827e3"
        static let ValeeratheHollow_DeathsShadow: String = "ICC_827p"
        static let ValeeratheHollow_ShadowReflectionToken: String = "ICC_827t"
        static let Shadowblade_ShadedEnchantment: String = "ICC_850e"
        static let ShadowReflectionTavernBrawl: String = "TB_ShadowReflection_001"
        static let FaldoreiStrider_SpiderAmbushEnchantment: String = "LOOT_026e"
        static let BinkTheBurglarHeroic: String = "LOOTA_BOSS_45h"
        static let ShadowofDeath_ShadowToken = "ULD_286t"
    }
}

extension CardIds.Secrets {
    struct Rogue {
        static let All = [CheatDeath, Evasion, SuddenBetrayal]
        static let CheatDeath = CardIds.Collectible.Rogue.CheatDeath
        static let Evasion = CardIds.Collectible.Rogue.Evasion
        static let SuddenBetrayal = CardIds.Collectible.Rogue.SuddenBetrayal
    }
}
