/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.Collectible {
    struct Rogue {
        static let ShadoPanRider: String = "AT_028"
        static let Buccaneer: String = "AT_029"
        static let UndercityValiant: String = "AT_030"
        static let Cutpurse: String = "AT_031"
        static let ShadyDealer: String = "AT_032"
        static let Burgle: String = "AT_033"
        static let PoisonedBlade: String = "AT_034"
        static let BeneathTheGrounds: String = "AT_035"
        static let Anubarak: String = "AT_036"
        static let GangUp: String = "BRM_007"
        static let DarkIronSkulker: String = "BRM_008"
        static let LuckydoBuccaneer: String = "CFM_342"
        static let CounterfeitCoin: String = "CFM_630"
        static let LotusAssassin: String = "CFM_634"
        static let ShadowRager: String = "CFM_636"
        static let JadeShuriken: String = "CFM_690"
        static let JadeSwarmer: String = "CFM_691"
        static let GadgetzanFerryman: String = "CFM_693"
        static let ShadowSensei: String = "CFM_694"
        static let ShakuTheCollector: String = "CFM_781"
        static let Backstab: String = "CS2_072"
        static let ColdBlood: String = "CS2_073"
        static let DeadlyPoison: String = "CS2_074"
        static let SinisterStrike: String = "CS2_075"
        static let GilblinStalker: String = "GVG_081"
        static let Assassinate: String = "CS2_076"
        static let Sprint: String = "CS2_077"
        static let AssassinsBlade: String = "CS2_080"
        static let BladeFlurry: String = "CS2_233"
        static let Eviscerate: String = "EX1_124"
        static let Betrayal: String = "EX1_126"
        static let Conceal: String = "EX1_128"
        static let FanOfKnives: String = "EX1_129"
        static let DefiasRingleader: String = "EX1_131"
        static let PerditionsBlade: String = "EX1_133"
        static let Si7Agent: String = "EX1_134"
        static let Headcrack: String = "EX1_137"
        static let Shadowstep: String = "EX1_144"
        static let Preparation: String = "EX1_145"
        static let Shiv: String = "EX1_278"
        static let PatientAssassin: String = "EX1_522"
        static let Sap: String = "EX1_581"
        static let EdwinVancleef: String = "EX1_613"
        static let AnubarAmbusher: String = "FP1_026"
        static let TinkersSharpswordOil: String = "GVG_022"
        static let GoblinAutoBarber: String = "GVG_023"
        static let CogmastersWrench: String = "GVG_024"
        static let OneEyedCheat: String = "GVG_025"
        static let IronSensei: String = "GVG_027"
        static let TradePrinceGallywix: String = "GVG_028"
        static let Sabotage: String = "GVG_047"
        static let OgreNinja: String = "GVG_088"
        static let ValeeraSanguinar: String = "HERO_03"
        static let MaievShadowsong: String = "HERO_03a"
        static let BoneBaron: String = "ICC_065"
        static let RollTheBones: String = "ICC_201"
        static let LeechingPoison: String = "ICC_221"
        static let Doomerang: String = "ICC_233"
        static let RuneforgeHaunter: String = "ICC_240"
        static let PlagueScientist: String = "ICC_809"
        static let LilianVoss: String = "ICC_811"
        static let ValeeraTheHollow: String = "ICC_827"
        static let Shadowblade: String = "ICC_850"
        static let SpectralPillager: String = "ICC_910"
        static let Swashburglar: String = "KAR_069"
        static let EtherealPeddler: String = "KAR_070"
        static let DeadlyFork: String = "KAR_094"
        static let PitSnake: String = "LOE_010"
        static let TombPillager: String = "LOE_012"
        static let UnearthedRaptor: String = "LOE_019"
        static let Vanish: String = "NEW1_004"
        static let Kidnapper: String = "NEW1_005"
        static let MasterOfDisguise: String = "NEW1_014"
        static let BladedCultist: String = "OG_070"
        static let JourneyBelow: String = "OG_072"
        static let ThistleTea: String = "OG_073"
        static let XarilPoisonedMind: String = "OG_080"
        static let ShadowStrike: String = "OG_176"
        static let SouthseaSquidface: String = "OG_267"
        static let BladeOfCthun: String = "OG_282"
        static let Shadowcaster: String = "OG_291"
        static let UndercityHuckster: String = "OG_330"
        static let RazorpetalVolley: String = "UNG_057"
        static let RazorpetalLasher: String = "UNG_058"
        static let MimicPod: String = "UNG_060"
        static let ObsidianShard: String = "UNG_061"
        static let Biteweed: String = "UNG_063"
        static let VilespineSlayer: String = "UNG_064"
        static let SherazinCorpseFlower: String = "UNG_065"
        static let TheCavernsBelow: String = "UNG_067"
        static let EnvenomWeapon: String = "UNG_823"
        static let Hallucination: String = "UNG_856"
        static let CheatDeath: String = "LOOT_204"
        static let Evasion: String = "LOOT_214"
        static let SuddenBetrayal: String = "LOOT_210"
        static let SonyaShadowdancer: String = "LOOT_165"
        static let FaldoreiStrider: String = "LOOT_026"
        static let Kingsbane: String = "LOOT_542"
        static let LabRecruiter: String = "BOT_288"
        static let ShadowOfDeath: String = "ULD_286"
        static let Bamboozle = "BT_042"
        static let Ambush = "BT_707"
        static let DirtyTricks = "BT_709"
        static let Plagiarize = "SCH_706"
        static let PlagiarizeCore = "CORE_SCH_706"
        static let ShadowClone = "DMF_513"
        static let Waxadred = "DRG_036"
        static let Akama = "BT_713"
        static let TogwagglesScheme = "DAL_010"
        static let BloodsailFlybooter = "DRG_035"
        static let UmbralSkulker = "DRG_027"
        static let BlinkFox = "GIL_827"
        static let AcademicEspionage = "BOT_087"
        static let Shenanigans = "YOP_017"
        static let WickedStabRank1 = "BAR_319"
        static let EfficientOctoBot = "BAR_320"
        static let MaestraOfTheMasquerade = "SW_050"
        static let Garrote = "SW_311"
        static let LoanShark = "SW_434"
        static let AzsharanVessel = "TSC_912"
        static let BootstrapSunkeneer = "TSC_933"
        static let SparkjoyCheat = "YOP_016"
        static let DoubleCross = "REV_825"
        static let Kidnap = "REV_828"
        static let StickySituation = "REV_827"
        static let Perjury = "MAW_018"
        static let Wanted = "GIL_687"
        static let AmbushInvalid = "CORE_BT_707"
        static let CheatDeathInvalid = "CORE_LOOT_204"
        static let PlagiarizeInvalid = "CORE_SCH_706"
        static let TombPillagerPLACEHOLDER_202204 = "CORE_LOE_012"
        static let TombPillagerWONDERS = "WON_340"
        static let CoppertailSnoop = "TTN_921"
        static let DartThrow = "WW_006"
        static let BountyWrangler = "WW_363"
        static let BloodrockCoShovel = "WW_412"
        static let DrillyTheKid = "WW_417"
        static let PogoHopper = "BOT_283"
        static let FaldoreiStriderInvalid = "CORE_LOOT_026"
        static let MetalDetector = "VAC_330"
        static let TentacleGrip = "YOG_526"
        static let DigForTreasure = "TOY_510"
        static let OhManager = "VAC_460"
        static let CloakOfShadows = "DMF_512"
        static let PreparationCore = "CORE_EX1_145"
        static let SandboxScoundrel = "TOY_521"
        static let SeaShill = "VAC_332"
        static let SecretPassage = "SCH_305"
        static let TarSlick = "TTN_726"
        static let TheCrystalCove = "TOY_512"
        static let ValeeraTheHollowICECROWN = "ICC_827"
        static let GalakrondTheNightmare = "DRG_610"
        static let JadeSwarmerWONDERS = "WON_067"
        static let JadeTelegram = "WON_078"
        static let JadeShurikenWONDERS = "WON_070"
        static let Talgath = "GDB_472"
        static let BackstabCore = "CORE_CS2_072"
        static let LuckyComet = "GDB_873"
        static let SpacerockCollector = "GDB_875"
        static let TessGreymane = "GIL_598"
        static let TessGreymaneCore = "CORE_GIL_598"
        static let TheGravitationalDisplacer = "GDB_466"
        static let ScroungingShipwright = "GDB_876"
        static let StarshipSchematic = "GDB_102"
        static let EverythingMustGo = "TOY_519"
        static let CounterfeitBlade = "SW_310"
    }
}

extension CardIds.NonCollectible {
    struct Rogue {
        static let WickedKnife: String = "CS2_082"
        static let DaggerMastery: String = "CS2_083b"
        static let SharpenedEnchantment: String = "CS2_083e"
        static let ColdBlood_ColdBloodEnchantment1: String = "CS2_073e"
        static let ColdBlood_ColdBloodEnchantment2: String = "CS2_073e2"
        static let DefiasRingleader_DefiasBanditToken: String = "EX1_131t"
        static let Preparation_PreparationEnchantment: String = "EX1_145o"
        static let EdwinVanCleef_VancleefsVengeanceEnchantment: String = "EX1_613e"
        static let MasterofDisguise_DisguisedEnchantment: String = "NEW1_014e"
        static let Conceal_ConcealedEnchantment: String = "EX1_128e"
        static let IronSensei_IronedOutEnchantment: String = "GVG_027e"
        static let ShadyDealer_ShadyDealsEnchantment: String = "AT_032e"
        static let PoisonedBlade_LacedEnchantment: String = "AT_034e"
        static let BeneaththeGrounds_NerubianAmbushToken: String = "AT_035t"
        static let Anubarak_NerubianToken: String = "AT_036t"
        static let JusticarTrueheart_PoisonedDaggers: String = "AT_132_ROGUE"
        static let JusticarTrueheart_PoisonedDagger: String = "AT_132_ROGUEt"
        static let RyanMasterson: String = "CRED_40"
        static let JusticarTrueheart_PoisonedDaggersHeroSkins: String = "AT_132_ROGUE_H1"
        static let JusticarTrueheart_PoisonedDaggerHeroSkins: String = "AT_132_ROGUEt_H1"
        static let WickedKnife_WickedKnifeHeroSkins: String = "CS2_082_H1"
        static let DaggerMasteryHeroSkins: String = "CS2_083b_H1"
        static let RogueTavernBrawl: String = "FB_LK_Rogue_copy"
        static let NextHeroRogueEnchCopy: String = "FB_LK_Rogue_Ench_copy"
        static let NextHeroRogueEnch: String = "FB_TagTeam_Rogue_Ench"
        static let SharpenedTavernBrawl: String = "TB_BlingBrawl_Hero1e"
        static let SharpenTavernBrawl: String = "TB_BlingBrawl_Hero1p"
        static let SecondClassRogueTavernBrawl: String = "TB_ClassRandom_Rogue"
        static let CastFromShadowTavernBrawl: String = "TB_CoOpv3_201"
        static let ShadowReflection_ShadowReflectionEnchantmentTavernBrawl: String = "TB_ShadowReflection_001e"
        static let FacilitatedTavernBrawl: String = "TB_Superfriends001e"
        static let DrawOffensivePlayTavernBrawl: String = "TB_Superfriends002e"
        static let CashIn: String = "TP_Bling_HP2"
        static let UnearthedRaptor_UnearthedRaptorEnchantment: String = "LOE_019e"
        static let BladedCultist_ThirstyBladesEnchantment: String = "OG_070e"
        static let XarilPoisonedMind_KingsbloodToxin: String = "OG_080b"
        static let XarilPoisonedMind_BloodthistleToxin: String = "OG_080c"
        static let XarilPoisonedMind_BriarthornToxin: String = "OG_080d"
        static let XarilPoisonedMind_FadeleafToxinEnchantment: String = "OG_080e"
        static let XarilPoisonedMind_FirebloomToxin: String = "OG_080f"
        static let SouthseaSquidface_SquidOilSheenEnchantment: String = "OG_267e"
        static let DeadlyFork_SharpFork: String = "KAR_094a"
        static let LuckydoBuccaneer_LootedBladeEnchantment: String = "CFM_342e"
        static let ShadowSensei_TrainedEnchantment: String = "CFM_694e"
        static let RazorpetalVolley_RazorpetalToken: String = "UNG_057t1"
        static let Biteweed_SproutEnchantment: String = "UNG_063e"
        static let SherazinCorpseFlower_SherazinSeedToken: String = "UNG_065t"
        static let TheCavernsBelow_CrystalCoreToken: String = "UNG_067t1"
        static let PhantomFreebooter_WittyWeaponplayEnchantment: String = "ICC_018e"
        static let LeechingPoison_LeechingPoisonEnchantment: String = "ICC_221e"
        static let RuneforgeHaunter_ResilientWeaponEnchantment: String = "ICC_240e"
        static let PlagueScientist_TestSubjectEnchantment: String = "ICC_809e"
        static let ValeeratheHollow_ShadowReflectionEnchantment: String = "ICC_827e"
        static let ValeeratheHollow_VeilOfShadowsEnchantment: String = "ICC_827e3"
        static let ValeeratheHollow_DeathsShadow: String = "ICC_827p"
        static let ValeeratheHollow_ShadowReflectionToken: String = "ICC_827t"
        static let Shadowblade_ShadedEnchantment: String = "ICC_850e"
        static let ShadowReflectionTavernBrawl: String = "TB_ShadowReflection_001"
        static let FaldoreiStrider_SpiderAmbushEnchantment: String = "LOOT_026e"
        static let BinkTheBurglarHeroic: String = "LOOTA_BOSS_45h"
        static let ShadowofDeath_ShadowToken = "ULD_286t"
        static let Waxadred_WaxadredsCandleToken = "DRG_036t"
        static let Akama_AkamaPrimeToken = "BT_713t"
        static let BloodsailFlybooter_SkyPirateToken = "DRG_035t"
        static let BottledTerror = "TRLA_106"
        static let TreasureFromBelow = "TRLA_186"
        static let PiratesMark = "TRLA_187"
        static let WickedStabRank1_WickedStabRank2Token = "BAR_319t"
        static let WickedStabRank1_WickedStabRank3Token = "BAR_319t2"
        static let Garrote_BleedToken = "SW_311t"
        static let AzsharanVessel_SunkenVesselToken = "TSC_912t"
        static let CamouflagedDirigible_CamouflagedEnchantment = "DRG_074e"
        static let CloakofShadows_SneakyEnchantment = "DMF_512e"
        static let Preparation_PreparationEnchantment2 = "EX1_145o"
        static let SandboxScoundrel_OnSaleEnchantment = "TOY_521e"
        static let SeaShill_SeaShillEnchantment = "VAC_332e"
        static let SecretPassage_SecretEntranceEnchantment = "SCH_305e2"
        static let TheCrystalCove_TreasuresBelowEnchantment = "TOY_512e1"
        static let KoboldMiner_TheAzeriteScorpionToken = "WW_001t23"
        static let LuckyComet_ComboCometEnchantment = "GDB_873e"
        static let SpacerockCollector_RockCollectionEnchantment = "GDB_875e"
        static let ArkoniteDefenseCrystal_TheScavengersWillToken = "GDB_100t8"
    }
}

extension CardIds.Secrets {
    struct Rogue {
        static let All = [Ambush, Bamboozle, CheatDeath, DirtyTricks, Evasion, Plagiarize,
                          ShadowClone, Shenanigans, SuddenBetrayal, DoubleCross, Kidnap,
                          StickySituation, Perjury]
        static let Ambush = MultiIdCard(CardIds.Collectible.Rogue.Ambush, CardIds.Collectible.Rogue.AmbushInvalid)
        static let Bamboozle = MultiIdCard(CardIds.Collectible.Rogue.Bamboozle)
        static let CheatDeath = MultiIdCard(CardIds.Collectible.Rogue.CheatDeath, CardIds.Collectible.Rogue.CheatDeathInvalid)
        static let DirtyTricks = MultiIdCard(CardIds.Collectible.Rogue.DirtyTricks)
        static let Evasion = MultiIdCard(CardIds.Collectible.Rogue.Evasion)
        static let Plagiarize = MultiIdCard(CardIds.Collectible.Rogue.Plagiarize, CardIds.Collectible.Rogue.PlagiarizeInvalid)
        static let ShadowClone = MultiIdCard(CardIds.Collectible.Rogue.ShadowClone)
        static let Shenanigans = MultiIdCard(CardIds.Collectible.Rogue.Shenanigans)
        static let SuddenBetrayal = MultiIdCard(CardIds.Collectible.Rogue.SuddenBetrayal)
        static let DoubleCross = MultiIdCard(CardIds.Collectible.Rogue.DoubleCross)
        static let Kidnap = MultiIdCard(CardIds.Collectible.Rogue.Kidnap)
        static let StickySituation = MultiIdCard(CardIds.Collectible.Rogue.StickySituation)
        static let Perjury = MultiIdCard(CardIds.Collectible.Rogue.Perjury)
    }
}
