/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.Collectible {
    struct Shaman {
        static let TuskarrTotemic = "AT_046"
        static let DraeneiTotemcarver = "AT_047"
        static let HealingWave = "AT_048"
        static let ThunderBluffValiant = "AT_049"
        static let ChargedHammer = "AT_050"
        static let ElementalDestruction = "AT_051"
        static let TotemGolem = "AT_052"
        static let AncestralKnowledge = "AT_053"
        static let TheMistcaller = "AT_054"
        static let LavaShock = "BRM_011"
        static let FireguardDestroyer = "BRM_012"
        static let JinyuWaterspeaker = "CFM_061"
        static let CallInTheFinishers = "CFM_310"
        static let JadeChieftain = "CFM_312"
        static let FindersKeepers = "CFM_313"
        static let WhiteEyes = "CFM_324"
        static let Devolve = "CFM_696"
        static let LotusIllusionist = "CFM_697"
        static let JadeLightning = "CFM_707"
        static let JadeClaws = "CFM_717"
        static let FrostShock = "CS2_037"
        static let AncestralSpirit = "CS2_038"
        static let Windfury = "CS2_039"
        static let AncestralHealing = "CS2_041"
        static let FireElemental = "CS2_042"
        static let RockbiterWeapon = "CS2_045"
        static let Bloodlust = "CS2_046"
        static let FarSight = "CS2_053"
        static let LightningBolt = "EX1_238"
        static let LavaBurst = "EX1_241"
        static let DustDevil = "EX1_243"
        static let TotemicMight = "EX1_244"
        static let EarthShock = "EX1_245"
        static let Hex = "EX1_246"
        static let StormforgedAxe = "EX1_247"
        static let FeralSpirit = "EX1_248"
        static let EarthElemental = "EX1_250"
        static let ForkedLightning = "EX1_251"
        static let UnboundElemental = "EX1_258"
        static let LightningStorm = "EX1_259"
        static let FlametongueTotem = "EX1_565"
        static let Doomhammer = "EX1_567"
        static let ManaTideTotem = "EX1_575"
        static let Windspeaker = "EX1_587"
        static let Reincarnate = "FP1_025"
        static let AncestorsCall = "GVG_029"
        static let Powermace = "GVG_036"
        static let WhirlingZapOMatic = "GVG_037"
        static let Crackle = "GVG_038"
        static let VitalityTotem = "GVG_039"
        static let SiltfinSpiritwalker = "GVG_040"
        static let Neptulon = "GVG_042"
        static let DunemaulShaman = "GVG_066"
        static let Thrall = "HERO_02"
        static let MorglTheOracle = "HERO_02a"
        static let WickedWitchdoctor = "KAR_021"
        static let SpiritClaws = "KAR_063"
        static let MaelstromPortal = "KAR_073"
        static let RumblingElemental = "LOE_016"
        static let TunnelTrogg = "LOE_018"
        static let EveryfinIsAwesome = "LOE_113"
        static let AlakirTheWindlord = "NEW1_010"
        static let PrimalFusion = "OG_023"
        static let FlamewreathedFaceless = "OG_024"
        static let EternalSentinel = "OG_026"
        static let Evolve = "OG_027"
        static let ThingFromBelow = "OG_028"
        static let HammerOfTwilight = "OG_031"
        static let Stormcrack = "OG_206"
        static let HallazealTheAscended = "OG_209"
        static let MasterOfEvolution = "OG_328"
    }
}

extension CardIds.NonCollectible {
    struct Shaman {
        static let AncestralHealing_AncestralInfusionEnchantment = "CS2_041e"
        static let RockbiterWeapon_RockbiterWeaponEnchantment = "CS2_045e"
        static let Bloodlust_BloodlustEnchantment = "CS2_046e"
        static let TotemicCall = "CS2_049"
        static let SearingTotem = "CS2_050"
        static let StoneclawTotem = "CS2_051"
        static let WrathOfAirTotem = "CS2_052"
        static let TotemicMight_TotemicMightEnchantment = "EX1_244e"
        static let Hex_HexxedEnchantment = "EX1_246e"
        static let FlametongueTotem_FlametongueEnchantment = "EX1_565o"
        static let HealingTotem = "NEW1_009"
        static let AncestralSpirit_AncestralSpiritEnchantment = "CS2_038e"
        static let FarSight_FarSightEnchantment = "CS2_053e"
        static let UnboundElemental_OverloadingEnchantment = "EX1_258e"
        static let SpiritWolf = "EX1_tk11"
        static let Powermace_PoweredEnchantment = "GVG_036e"
        static let LavaShock_LavaShockToken = "BRM_011t"
        static let DraeneiTotemcarver_ExperiencedEnchantment = "AT_047e"
        static let ThunderBluffValiant_PowerOfTheBluffEnchantment = "AT_049e"
        static let ChargedHammer_LightningJoltToken = "AT_050t"
        static let JusticarTrueheart_TotemicSlam = "AT_132_SHAMAN"
        static let JusticarTrueheart_HealingTotem = "AT_132_SHAMANa"
        static let JusticarTrueheart_SearingTotem = "AT_132_SHAMANb"
        static let JusticarTrueheart_StoneclawTotem = "AT_132_SHAMANc"
        static let JusticarTrueheart_WrathOfAirTotem = "AT_132_SHAMANd"
        static let TotemicCall_TotemicCallHeroSkins = "CS2_049_H1"
        static let TotemicSlamHeroSkins = "CS2_049_H1_AT_132"
        static let SecondClassShamanTavernBrawl = "TB_ClassRandom_Shaman"
        static let ElementalEruptionTavernBrawl = "TB_CoOpv3_006"
        static let TunnelTrogg_TroggNoStupidEnchantment = "LOE_018e"
        static let HammerofTwilight_TwilightElemental = "OG_031a"
        static let EvolveTavernBrawl = "TB_OG_027"
        static let CallintheFinishers_MurlocRazorgillToken = "CFM_310t"
        static let WhiteEyes_TheStormGuardianToken = "CFM_324t"
    }
}
