/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.Collectible {
    struct Warlock {
        static let Dreadsteed = "AT_019"
        static let FearsomeDoomguard = "AT_020"
        static let TinyKnightOfEvil = "AT_021"
        static let FistOfJaraxxus = "AT_022"
        static let VoidCrusher = "AT_023"
        static let Demonfuse = "AT_024"
        static let DarkBargain = "AT_025"
        static let Wrathguard = "AT_026"
        static let WilfredFizzlebang = "AT_027"
        static let Demonwrath = "BRM_005"
        static let ImpGangBoss = "BRM_006"
        static let FelfirePotion = "CFM_094"
        static let BlastcrystalPotion = "CFM_608"
        static let Crystalweaver = "CFM_610"
        static let BloodfuryPotion = "CFM_611"
        static let KabalTrafficker = "CFM_663"
        static let SeadevilStinger = "CFM_699"
        static let KrulTheUnshackled = "CFM_750"
        static let AbyssalEnforcer = "CFM_751"
        static let UnlicensedApothecary = "CFM_900"
        static let ShadowBolt = "CS2_057"
        static let BloodImp = "CS2_059"
        static let DrainLife = "CS2_061"
        static let Hellfire = "CS2_062"
        static let Corruption = "CS2_063"
        static let DreadInfernal = "CS2_064"
        static let Voidwalker = "CS2_065"
        static let Felguard = "EX1_301"
        static let MortalCoil = "EX1_302"
        static let Shadowflame = "EX1_303"
        static let VoidTerror = "EX1_304"
        static let Succubus = "EX1_306"
        static let Soulfire = "EX1_308"
        static let SiphonSoul = "EX1_309"
        static let Doomguard = "EX1_310"
        static let TwistingNether = "EX1_312"
        static let PitLord = "EX1_313"
        static let SummoningPortal = "EX1_315"
        static let PowerOverwhelming = "EX1_316"
        static let SenseDemons = "EX1_317"
        static let FlameImp = "EX1_319"
        static let BaneOfDoom = "EX1_320"
        static let LordJaraxxus = "EX1_323"
        static let Demonfire = "EX1_596"
        static let Voidcaller = "FP1_022"
        static let Darkbomb = "GVG_015"
        static let MistressOfPain = "GVG_018"
        static let Demonheart = "GVG_019"
        static let FelCannon = "GVG_020"
        static let Malganis = "GVG_021"
        static let ImpLosion = "GVG_045"
        static let AnimaGolem = "GVG_077"
        static let FloatingWatcher = "GVG_100"
        static let Guldan = "HERO_07"
        static let KaraKazham = "KAR_025"
        static let MalchezaarsImp = "KAR_089"
        static let SilverwareGolem = "KAR_205"
        static let CurseOfRafaam = "LOE_007"
        static let DarkPeddler = "LOE_023"
        static let ReliquarySeeker = "LOE_116"
        static let SacrificialPact = "NEW1_003"
        static let DarkshireLibrarian = "OG_109"
        static let DarkshireCouncilman = "OG_113"
        static let ForbiddenRitual = "OG_114"
        static let SpreadingMadness = "OG_116"
        static let RenounceDarkness = "OG_118"
        static let Chogall = "OG_121"
        static let Doom = "OG_239"
        static let PossessedVillager = "OG_241"
        static let UsherOfSouls = "OG_302"
    }
}

extension CardIds.NonCollectible {
    struct Warlock {
        static let LifeTap = "CS2_056"
        static let Corruption_CorruptionEnchantment = "CS2_063e"
        static let BloodImp_BloodPactEnchantment = "CS2_059o"
        static let VoidTerror_ConsumeEnchantment = "EX1_304e"
        static let PowerOverwhelming_PowerOverwhelmingEnchantment = "EX1_316e"
        static let SenseDemons_WorthlessImpToken = "EX1_317t"
        static let LordJaraxxusHeroic = "EX1_323h"
        static let LordJaraxxus_BloodFury = "EX1_323w"
        static let Demonfire_DemonfireEnchantment = "EX1_596e"
        static let Inferno = "EX1_tk33"
        static let Infernal = "EX1_tk34"
        static let HeiganTheUnclean = "NAX5_01"
        static let HeiganTheUncleanHeroic = "NAX5_01H"
        static let Demonheart_DemonheartEnchantment = "GVG_019e"
        static let MalGanis_GraspOfMalganisEnchantment = "GVG_021e"
        static let Implosion_ImpToken = "GVG_045t"
        static let FloatingWatcher_BrowFurrowEnchantment = "GVG_100e"
        static let ImpGangBoss_ImpToken = "BRM_006t"
        static let TinyKnightofEvil_FelrageEnchantment = "AT_021e"
        static let WilfredFizzlebang_MasterSummonerEnchantment = "AT_027e"
        static let JusticarTrueheart_SoulTap = "AT_132_WARLOCK"
        static let SecondClassWarlockTavernBrawl = "TB_ClassRandom_Warlock"
        static let DarkWandererTavernBrawl = "TB_SPT_DPromo_Hero"
        static let TwistingNetherTavernBrawl = "TB_SPT_DpromoEX1_312"
        static let CurseofRafaam_CursedToken = "LOE_007t"
        static let ObsidianDestroyer_SinisterPowerEnchantment = "LOE_009e"
        static let DarkshireCouncilman_PowerOfThePeopleEnchantment = "OG_113e"
        static let ForbiddenRitual_IckyTentacle = "OG_114a"
        static let PossessedVillager_Shadowbeast = "OG_241a"
        static let KaraKazham_Candle = "KAR_025a"
        static let KaraKazham_Broom = "KAR_025b"
        static let KaraKazham_Teapot = "KAR_025c"
        static let Legion_Abyssal = "KARA_00_02a"
        static let Kilrek = "KARA_09_08"
        static let Kilrek_Kilrek = "KARA_09_08_heroic"
    }
}
