/*
 This file is generated by https://github.com/HearthSim/HearthDb

 The MIT License (MIT)

 Copyright (c) 2016 HearthSim

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.

 Source: https://github.com/HearthSim/HearthDb

 */

import Foundation

extension CardIds.Collectible {
    struct Warrior {
        static let Bash: String = "AT_064"
        static let KingsDefender: String = "AT_065"
        static let OrgrimmarAspirant: String = "AT_066"
        static let MagnataurAlpha: String = "AT_067"
        static let Bolster: String = "AT_068"
        static let SparringPartner: String = "AT_069"
        static let AlexstraszasChampion: String = "AT_071"
        static let VarianWrynn: String = "AT_072"
        static let SeaReaver: String = "AT_130"
        static let Revenge: String = "BRM_015"
        static let AxeFlinger: String = "BRM_016"
        static let PublicDefender: String = "CFM_300"
        static let BrassKnuckles: String = "CFM_631"
        static let HobartGrapplehammer: String = "CFM_643"
        static let SleepWithTheFishes: String = "CFM_716"
        static let StolenGoods: String = "CFM_752"
        static let GrimyGadgeteer: String = "CFM_754"
        static let GrimestreetPawnbroker: String = "CFM_755"
        static let AlleyArmorsmith: String = "CFM_756"
        static let IKnowAGuy: String = "CFM_940"
        static let Charge: String = "CS2_103"
        static let Rampage: String = "CS2_104"
        static let HeroicStrike: String = "CS2_105"
        static let FieryWarAxe: String = "CS2_106"
        static let Execute: String = "CS2_108"
        static let ArcaniteReaper: String = "CS2_112"
        static let Cleave: String = "CS2_114"
        static let WarsongCommander: String = "EX1_084"
        static let Slam: String = "EX1_391"
        static let BattleRage: String = "EX1_392"
        static let ArathiWeaponsmith: String = "EX1_398"
        static let Whirlwind: String = "EX1_400"
        static let Armorsmith: String = "EX1_402"
        static let Brawl: String = "EX1_407"
        static let MortalStrike: String = "EX1_408"
        static let Upgrade: String = "EX1_409"
        static let ShieldSlam: String = "EX1_410"
        static let Gorehowl: String = "EX1_411"
        static let GrommashHellscream: String = "EX1_414"
        static let CruelTaskmaster: String = "EX1_603"
        static let FrothingBerserker: String = "EX1_604"
        static let ShieldBlock: String = "EX1_606"
        static let InnerRage: String = "EX1_607"
        static let DeathsBite: String = "FP1_021"
        static let BouncingBlade: String = "GVG_050"
        static let Warbot: String = "GVG_051"
        static let Crush: String = "GVG_052"
        static let Shieldmaiden: String = "GVG_053"
        static let OgreWarmaul: String = "GVG_054"
        static let ScrewjankClunker: String = "GVG_055"
        static let IronJuggernaut: String = "GVG_056"
        static let SiegeEngine: String = "GVG_086"
        static let GarroshHellscream: String = "HERO_01"
        static let MagniBronzebeard: String = "HERO_01a"
        static let MountainfireArmor: String = "ICC_062"
        static let BloodRazor: String = "ICC_064"
        static let DeadMansHand: String = "ICC_091"
        static let AnimatedBerserker: String = "ICC_238"
        static let ForgeOfSouls: String = "ICC_281"
        static let Rotface: String = "ICC_405"
        static let ValkyrSoulclaimer: String = "ICC_408"
        static let DeathRevenant: String = "ICC_450"
        static let ScourgelordGarrosh: String = "ICC_834"
        static let BringItOn: String = "ICC_837"
        static let ProtectTheKing: String = "KAR_026"
        static let FoolsBane: String = "KAR_028"
        static let IronforgePortal: String = "KAR_091"
        static let ObsidianDestroyer: String = "LOE_009"
        static let FierceMonkey: String = "LOE_022"
        static let CursedBlade: String = "LOE_118"
        static let KorkronElite: String = "NEW1_011"
        static let CommandingShout: String = "NEW1_036"
        static let TentaclesForArms: String = "OG_033"
        static let RavagingGhoul: String = "OG_149"
        static let BloodhoofBrave: String = "OG_218"
        static let Malkorok: String = "OG_220"
        static let BloodWarriors: String = "OG_276"
        static let AncientShieldbearer: String = "OG_301"
        static let NzothsFirstMate: String = "OG_312"
        static let BloodToIchor: String = "OG_314"
        static let BloodsailCultist: String = "OG_315"
        static let TarLord: String = "UNG_838"
        static let ExploreUngoro: String = "UNG_922"
        static let IronHide: String = "UNG_923"
        static let OrneryDirehorn: String = "UNG_925"
        static let CorneredSentry: String = "UNG_926"
        static let SuddenGenesis: String = "UNG_927"
        static let MoltenBlade: String = "UNG_929"
        static let KingMosh: String = "UNG_933"
        static let FirePlumesHeart: String = "UNG_934"
        static let DirehornHatchling: String = "UNG_957"
        static let ClockworkGoblin: String = "DAL_060"
        static let Wrenchcalibur: String = "DAL_063"
    }
}

extension CardIds.NonCollectible {
    struct Warrior {
        static let ArmorUp: String = "CS2_102"
        static let Charge_ChargeEnchantment: String = "CS2_103e2"
        static let HeroicStrike_HeroicStrikeEnchantment: String = "CS2_105e"
        static let WarsongCommander_ChargeEnchantment: String = "EX1_084e"
        static let Rampage_RampageEnchantment: String = "CS2_104e"
        static let ArathiWeaponsmith_BattleAxeToken: String = "EX1_398t"
        static let Upgrade_UpgradedEnchantment: String = "EX1_409e"
        static let Upgrade_HeavyAxeToken: String = "EX1_409t"
        static let Gorehowl_BloodrageEnchantment: String = "EX1_411e"
        static let Gorehowl_NeedsSharpeningEnchantment: String = "EX1_411e2"
        static let GrommashHellscream_EnragedEnchantment: String = "EX1_414e"
        static let CruelTaskmaster_WhippedIntoShapeEnchantment: String = "EX1_603e"
        static let FrothingBerserker_BerserkEnchantment: String = "EX1_604o"
        static let InnerRage_InnerRageEnchantment: String = "EX1_607e"
        static let CommandingShout_CommandingShoutEnchantment1: String = "NEW1_036e"
        static let CommandingShout_CommandingShoutEnchantment2: String = "NEW1_036e2"
        static let Warbot_EnragedEnchantment: String = "GVG_051e"
        static let ScrewjankClunker_ScrewyJankEnchantment: String = "GVG_055e"
        static let IronJuggernaut_BurrowingMineToken: String = "GVG_056t"
        static let SiegeEngine_ArmorPlatedEnchantment: String = "GVG_086e"
        static let OrgrimmarAspirant_ForgesOfOrgrimmarEnchantment: String = "AT_066e"
        static let Bolster_BolsteredEnchantment: String = "AT_068e"
        static let SparringPartner_TrainingCompleteEnchantment: String = "AT_069e"
        static let AlexstraszasChampion_AlexstraszasBoonEnchantment: String = "AT_071e"
        static let JusticarTrueheart_TankUp: String = "AT_132_WARRIOR"
        static let ArmorUp_ArmorUpHeroSkins: String = "CS2_102_H1"
        static let TankUpHeroSkins: String = "CS2_102_H1_AT_132"
        static let WarriorTavernBrawl: String = "FB_LK_Warrior_copy"
        static let NextHeroWarriorEnchCopy: String = "FB_LK_Warrior_Ench_copy"
        static let NextHeroWarriorEnch: String = "FB_TagTeam_Warrior_Ench"
        static let SecondClassWarriorTavernBrawl: String = "TB_ClassRandom_Warrior"
        static let ChargeEnchantmentTavernBrawl: String = "TB_MP_01e"
        static let TheCowKingTavernBrawl: String = "TB_SPT_DPromo_Hero2"
        static let VisionsOfTheAssassinTavernBrawl: String = "TB_SPT_DPromoSecre8"
        static let VisionsOfTheBarbarianTavernBrawl: String = "TB_SPT_DPromoSecret1"
        static let VisionsOfHateTavernBrawl: String = "TB_SPT_DPromoSecret10"
        static let VisionsOfTheCrusaderTavernBrawl: String = "TB_SPT_DPromoSecret2"
        static let VisionsOfValorTavernBrawl: String = "TB_SPT_DPromoSecret3"
        static let VisionsOfFateTavernBrawl: String = "TB_SPT_DPromoSecret4"
        static let VisionsOfTheAmazonTavernBrawl: String = "TB_SPT_DPromoSecret5"
        static let VisionsOfTheSorcererTavernBrawl: String = "TB_SPT_DPromoSecret6"
        static let VisionsOfTheNecromancerTavernBrawl: String = "TB_SPT_DPromoSecret7"
        static let VisionsOfKnowledgeTavernBrawl: String = "TB_SPT_DPromoSecret9"
        static let ObsidianDestroyer_ScarabToken: String = "LOE_009t"
        static let CursedBlade_CursedBladeEnchantment: String = "LOE_118e"
        static let RustyHook: String = "OG_058"
        static let NZothsFirstMate_UpgradedEnchantment: String = "OG_312e"
        static let BloodToIchor_Slime: String = "OG_314b"
        static let ProtecttheKing_PawnToken: String = "KAR_026t"
        static let NazraWildaxe: String = "KARA_13_01"
        static let NazraWildaxeHeroic: String = "KARA_13_01H"
        static let TheHorde: String = "KARA_13_02"
        static let TheHordeHeroic: String = "KARA_13_02H"
        static let OrcWarrior: String = "KARA_13_03"
        static let OrcWarriorHeroic: String = "KARA_13_03H"
        static let HobartGrapplehammer_SmugglingEnchantment1: String = "CFM_643e"
        static let HobartGrapplehammer_SmugglingEnchantment2: String = "CFM_643e2"
        static let ExploreUnGoro_ChooseYourPathToken: String = "UNG_922t1"
        static let MoltenBlade_MagmicEnchantment: String = "UNG_929e"
        static let FirePlumesHeart_SulfurasToken: String = "UNG_934t1"
        static let DirehornHatchling_DirehornMatriarchToken: String = "UNG_957t1"
        static let BladestormHeroic: String = "ICC_834h"
        static let ScourgelordGarrosh_Shadowmourne: String = "ICC_834w"
    }
}

